FROM registry.access.redhat.com/ubi8/python-39:latest
WORKDIR $APP_ROOT
USER root

# install related pip dependencies
ENV PIP_DEFAULT_TIMEOUT=100
RUN pip install --upgrade pip
RUN pip install tox

#copy the src files
COPY . .

#Add command to run tox
CMD ["tox"]
