services:
  rbac-server:
      container_name: rbac_server
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /rbac
      entrypoint:
        - ./scripts/entrypoint.sh
      environment:
        - DATABASE_SERVICE_NAME=POSTGRES_SQL
        - DATABASE_ENGINE=postgresql
        - DATABASE_NAME=postgres
        - POSTGRES_SQL_SERVICE_HOST=db
        - POSTGRES_SQL_SERVICE_PORT=5432
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - API_PATH_PREFIX=/api/rbac
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - DJANGO_LOG_HANDLERS=console,ecs
        - DJANGO_READ_DOT_ENV_FILE=True
        - DEVELOPMENT=${DEVELOPMENT-False}
        - DJANGO_DEBUG=${DJANGO_DEBUG-True}
        - REDIS_HOST=${REDIS_HOST-rbac_redis}
        - PRINCIPAL_PROXY_SERVICE_PROTOCOL=${PRINCIPAL_PROXY_SERVICE_PROTOCOL-https}
        - PRINCIPAL_PROXY_SERVICE_PORT=${PRINCIPAL_PROXY_SERVICE_PORT-443}
        - PRINCIPAL_PROXY_SERVICE_HOST=${PRINCIPAL_PROXY_SERVICE_HOST}
        - PRINCIPAL_PROXY_USER_ENV=${PRINCIPAL_PROXY_USER_ENV-stage}
        - PRINCIPAL_PROXY_CLIENT_ID=${PRINCIPAL_PROXY_CLIENT_ID-insights-rbac}
        - PRINCIPAL_PROXY_API_TOKEN=${PRINCIPAL_PROXY_API_TOKEN}
        - BYPASS_BOP_VERIFICATION=${BYPASS_BOP_VERIFICATION-True}
        - PRINCIPAL_PROXY_SERVICE_PATH=${PRINCIPAL_PROXY_SERVICE_PATH}
        - PRINCIPAL_PROXY_SERVICE_SOURCE_CERT=${PRINCIPAL_PROXY_SERVICE_SOURCE_CERT-False}
        - PRINCIPAL_PROXY_SERVICE_SSL_VERIFY=${PRINCIPAL_PROXY_SERVICE_SSL_VERIFY-False}
        - RBAC_DESTRUCTIVE_API_ENABLED_UNTIL=${RBAC_DESTRUCTIVE_API_ENABLED_UNTIL}
        - RBAC_DESTRUCTIVE_SEEDING_ENABLED_UNTIL=${RBAC_DESTRUCTIVE_SEEDING_ENABLED_UNTIL}
      privileged: true
      ports:
          - 9080:8080
      volumes:
        - '.:/rbac/'
      depends_on:
        db:
          condition: service_healthy
        rbac-worker:
          condition: service_healthy
        rbac-scheduler:
          condition: service_healthy
      healthcheck:
        test: curl -q http://localhost:8080/metrics
        interval: 5s
        timeout: 5s
        retries: 10

  rbac-worker:
      container_name: rbac_worker
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /opt/rbac/rbac
      entrypoint: ['celery', '--broker=redis://redis:6379/0', '-A', 'rbac.celery', 'worker', '--loglevel=INFO']
      privileged: true
      depends_on:
        redis:
          condition: service_healthy
      healthcheck:
        test: [ "CMD-SHELL", "celery --broker=redis://redis:6379/0 -A rbac.celery status" ]
        interval: 30s
        timeout: 10s
        retries: 3

  rbac-scheduler:
      container_name: rbac_scheduler
      build:
          context: .
          dockerfile: Dockerfile
      working_dir: /opt/rbac/rbac
      entrypoint: ['celery', '--broker=redis://redis:6379/0', '-A', 'rbac.celery', 'beat', '--loglevel=INFO']
      privileged: true
      depends_on:
        redis:
          condition: service_healthy
      healthcheck:
        test: [ "CMD-SHELL", "celery --broker=redis://redis:6379/0 -A rbac.celery status" ]
        interval: 30s
        timeout: 10s
        retries: 3

  redis:
    container_name: rbac_redis
    image: redis:5.0.4
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  db:
    container_name: rbac_db
    image: postgres:14.5
    command: [
      "postgres", "-c", "wal_level=logical"
    ]
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  zookeeper:
    container_name: rbac_zookeeper
    image: registry.redhat.io/amq-streams/kafka-37-rhel9:2.7.0-6
    command: [
      "sh", "-c", "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2191"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    container_name: rbac_kafka
    image: registry.redhat.io/amq-streams/kafka-37-rhel9:2.7.0-6
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}"
    ]
    depends_on:
      - zookeeper
    mem_limit: 500m
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "storage-topic:1:1:compact,global-id-topic:1:1:compact,input-topic:1:1:compact,logx-topic:1:1:compact,dbx-topic:1:1:compact"
      KAFKA_HEAP_OPTS: "-Xmx500M -Xms500M"

  kafka_connect:
    container_name: rbac_kafka_connect
    image: quay.io/cloudservices/kafka-connect:57decfc
    command: [
      "sh", "-c", "bin/connect-distributed.sh /opt/kafka/config/rebac_connect.properties"
    ]
    depends_on:
      - kafka
    mem_limit: 500m
    ports:
      - "8083:8083"
    volumes:
      - ./scripts/debezium/rebac_connect.properties:/opt/kafka/config/rebac_connect.properties

  wait_for_app:
    container_name: wait_for_app
    image: hello-world:latest
    depends_on:
      rbac-server:
        condition: service_healthy

volumes:
  pg_data:

networks:
  default:
    name: rbac-network
    external: true
