version: '3'
services:
  roles_test:
      build:
          context: .
          dockerfile: Dockerfile-test
      working_dir: /rbac
      entrypoint: 'tox -r'
      environment:
        - DATABASE_HOST=db
        - DATABASE_PORT=15432
        - ACCESS_CACHE_ENABLED=False
        - BYPASS_BOP_VERIFICATION=True
      volumes:
        - '.:/rbac/'
      links:
        - db

  db:
    image: postgres:9.6
    environment:
    - POSTGRES_DB=rbac_test
    - POSTGRES_USER=postgres
    ports:
      - "15433:5432"
    volumes:
      - ./pg_data:/var/lib/pgsql/data
