#!/bin/bash

#npm install -g @typespec/compiler
#npm install @typespec/http
#npm install @typespec/rest
#npm install @typespec/openapi3
#npm install @typespec/versioning
#npm install @typespec/json-schema
#tsp install

tsp compile main.tsp
tsp compile main.tsp --options @typespec/openapi3.output-file=openapi.json

cp tsp-output/@typespec/openapi3/openapi.{yaml,json} ../v2
