# noqa


RH_IDENTITY_HEADER = "HTTP_X_RH_IDENTITY"
RH_INSIGHTS_REQUEST_ID = "HTTP_X_RH_INSIGHTS_REQUEST_ID"
RH_RBAC_PSK = "HTTP_X_RH_RBAC_PSK"
RH_RBAC_ACCOUNT = "HTTP_X_RH_RBAC_ACCOUNT"
RH_RBAC_CLIENT_ID = "HTTP_X_RH_RBAC_CLIENT_ID"
