--- 
apiVersion: cloud.redhat.com/v1alpha1
kind: ClowdEnvironment
metadata:
  name: rbac-test
spec:
  targetNamespace: rbac-test
  providers:
    web:
      port: 8000
      mode: operator
    metrics:
      port: 9000
      mode: operator
      path: "/metrics"
    kafka:
      namespace: default
      clusterName: rbac-cluster
      mode: local
    db:
      image: "registry.redhat.io/rhel8/postgresql-12:1-36"
      mode: local
    logging:
      mode: none
    objectStore:
      mode: minio
      port: 9000
    inMemoryDb:
      mode: redis
  resourceDefaults:
    limits: 
      cpu: "500m"
      memory: "8192Mi"
    requests:
      cpu: "300m"
      memory: "1024Mi"
