---
apiVersion: v1
kind: Template
metadata:
  name: rbac
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: rbac
  spec:
    envName: ${ENV_NAME}
    pods:
    - name: service
      image: ${IMAGE}:${IMAGE_TAG}
      minReplicas: 1
      web: true
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 8000
          scheme: HTTP
        initialDelaySeconds: 35
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 120
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: 8000
          scheme: HTTP
        initialDelaySeconds: 35
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 120
      volumes:
      - configMap:
          name: ${CONFIG_MAP_NAME}
        name: default-role-config
      - configMap:
          name: ${MODEL_ACCESS_PERMISSIONS}
        name: model-access-permissions
      volumeMounts:
      - mountPath: /opt/app-root/src/rbac/management/role/definitions
        name: default-role-config
      - mountPath: /opt/app-root/src/rbac/management/role/permissions
        name: model-access-permissions
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: 200m
          memory: 256Mi
      env:
        - name: SERVICE_PSKS
          valueFrom:
            secretKeyRef:
              key: psks.json
              name: ${RBAC_PSKS}
              optional: false
        - name: PGSSLMODE
          value: ${PGSSLMODE}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: rbac-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_PROTOCOL
          valueFrom:
            secretKeyRef:
              key: principal-proxy-protocol
              name: rbac-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              key: principal-proxy-host
              name: rbac-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_PORT
          valueFrom:
            secretKeyRef:
              key: principal-proxy-port
              name: rbac-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_PATH
          value: ''
        - name: PRINCIPAL_PROXY_USER_ENV
          valueFrom:
            secretKeyRef:
              key: principal-proxy-env
              name: rbac-secret
              optional: false
        - name: PRINCIPAL_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: principal-proxy-client-id
              name: rbac-secret
              optional: false
        - name: PRINCIPAL_PROXY_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: principal-proxy-api-token
              name: rbac-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_SSL_VERIFY
          valueFrom:
            secretKeyRef:
              key: principal-proxy-ssl-verify
              name: rbac-secret
              optional: true
        - name: PRINCIPAL_PROXY_SERVICE_SOURCE_CERT
          valueFrom:
            secretKeyRef:
              key: principal-proxy-source-cert
              name: rbac-secret
              optional: true
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: rbac
              resource: limits.cpu
        - name: ACCESS_CACHE_ENABLED
          value: ${ACCESS_CACHE_ENABLED}
        - name: APP_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DJANGO_DEBUG
          value: ${DJANGO_DEBUG}
        - name: API_PATH_PREFIX
          value: ${API_PATH_PREFIX}
        - name: DEVELOPMENT
          value: ${DEVELOPMENT}
        - name: RBAC_LOG_LEVEL
          value: ${RBAC_LOG_LEVEL}
        - name: DJANGO_LOG_LEVEL
          value: ${DJANGO_LOG_LEVEL}
        - name: DJANGO_LOG_FORMATTER
          value: ${DJANGO_LOG_FORMATTER}
        - name: DJANGO_LOG_HANDLERS
          value: ${DJANGO_LOG_HANDLERS}
        - name: DJANGO_LOG_DIRECTORY
          value: ${DJANGO_LOG_DIRECTORY}
        - name: DJANGO_LOGGING_FILE
          value: ${DJANGO_LOGGING_FILE}
        - name: PERMISSION_SEEDING_ENABLED
          value: ${PERMISSION_SEEDING_ENABLED}
        - name: ROLE_SEEDING_ENABLED
          value: ${ROLE_SEEDING_ENABLED}
        - name: GROUP_SEEDING_ENABLED
          value: ${GROUP_SEEDING_ENABLED}
        - name: DISABLE_MIGRATE
          value: ${DISABLE_MIGRATE}
        - name: BYPASS_BOP_VERIFICATION
          value: ${BYPASS_BOP_VERIFICATION}
        - name: ROLE_CREATE_ALLOW_LIST
          value: ${ROLE_CREATE_ALLOW_LIST}
        - name: RBAC_DESTRUCTIVE_ENABLED_UNTIL
          value: ${RBAC_DESTRUCTIVE_ENABLED_UNTIL}
    - name: worker
      image: ${IMAGE}:${IMAGE_TAG}
      minReplicas: 1
      livenessProbe:
        exec:
          command:
          - /bin/bash
          - -c
          - 'PYTHONPATH=${PWD}/rbac/ scl enable rh-python36 -- celery inspect
            ping -A rbac.celery

            '
        failureThreshold: 3
        initialDelaySeconds: 30
        periodSeconds: 300
        successThreshold: 1
        timeoutSeconds: 10
      readinessProbe:
        exec:
          command:
          - /bin/bash
          - -c
          - 'PYTHONPATH=${PWD}/rbac/ scl enable rh-python36 -- celery inspect
            ping -A rbac.celery

            '
        failureThreshold: 3
        periodSeconds: 300
        successThreshold: 1
        timeoutSeconds: 10
      volumeMounts:
      - mountPath: /opt/app-root/src/rbac/management/role/definitions
        name: default-role-config
      - mountPath: /opt/app-root/src/rbac/management/role/permissions
        name: model-access-permissions
      volumes:
      - configMap:
          name: ${CONFIG_MAP_NAME}
        name: default-role-config
      - configMap:
          name: ${MODEL_ACCESS_PERMISSIONS}
        name: model-access-permissions
      resources:
        limits:
          cpu: ${CELERY_WORKER_CPU_LIMIT}
          memory: ${CELERY_WORKER_MEMORY_LIMIT}
        requests:
          cpu: ${CELERY_WORKER_CPU_REQUEST}
          memory: ${CELERY_WORKER_MEMORY_REQUEST}
      env:
        - name: DJANGO_LOG_LEVEL
          value: ${DJANGO_LOG_LEVEL}
        - name: DJANGO_DEBUG
          value: ${DJANGO_DEBUG}
        - name: PERMISSION_SEEDING_ENABLED
          value: 'False'
        - name: ROLE_SEEDING_ENABLED
          value: 'False'
        - name: GROUP_SEEDING_ENABLED
          value: 'False'
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: ${NAME}-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_PROTOCOL
          valueFrom:
            secretKeyRef:
              key: principal-proxy-protocol
              name: ${NAME}-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_HOST
          valueFrom:
            secretKeyRef:
              key: principal-proxy-host
              name: ${NAME}-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_PORT
          valueFrom:
            secretKeyRef:
              key: principal-proxy-port
              name: ${NAME}-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_PATH
          value: ''
        - name: PRINCIPAL_PROXY_USER_ENV
          valueFrom:
            secretKeyRef:
              key: principal-proxy-env
              name: ${NAME}-secret
              optional: false
        - name: PRINCIPAL_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: principal-proxy-client-id
              name: ${NAME}-secret
              optional: false
        - name: PRINCIPAL_PROXY_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: principal-proxy-api-token
              name: ${NAME}-secret
              optional: false
        - name: PRINCIPAL_PROXY_SERVICE_SSL_VERIFY
          valueFrom:
            secretKeyRef:
              key: principal-proxy-ssl-verify
              name: ${NAME}-secret
              optional: true
        - name: PRINCIPAL_PROXY_SERVICE_SOURCE_CERT
          valueFrom:
            secretKeyRef:
              key: principal-proxy-source-cert
              name: ${NAME}-secret
              optional: true
        - name: APP_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PGSSLMODE
          value: ${PGSSLMODE}
    - name: scheduler
      image: ${IMAGE}:${IMAGE_TAG}
      minReplicas: 1
      livenessProbe:
        exec:
          command:
          - /bin/bash
          - -c
          - 'PYTHONPATH=${PWD}/rbac/ scl enable rh-python36 -- celery inspect
            ping -A rbac.celery

            '
        failureThreshold: 3
        initialDelaySeconds: 30
        periodSeconds: 300
        successThreshold: 1
        timeoutSeconds: 10
      readinessProbe:
        exec:
          command:
          - /bin/bash
          - -c
          - 'PYTHONPATH=${PWD}/rbac/ scl enable rh-python36 -- celery inspect
            ping -A rbac.celery

            '
        failureThreshold: 3
        periodSeconds: 300
        successThreshold: 1
        timeoutSeconds: 10
      resources:
        limits:
          cpu: ${CELERY_SCHEDULER_CPU_LIMIT}
          memory: ${CELERY_SCHEDULER_MEMORY_LIMIT}
        requests:
          cpu: ${CELERY_SCHEDULER_CPU_REQUEST}
          memory: ${CELERY_SCHEDULER_MEMORY_REQUEST}
      env:
      - name: DJANGO_LOG_LEVEL
        value: ${DJANGO_LOG_LEVEL}
      - name: DJANGO_DEBUG
        value: ${DJANGO_DEBUG}
      - name: APP_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PERMISSION_SEEDING_ENABLED
        value: 'False'
      - name: ROLE_SEEDING_ENABLED
        value: 'False'
      - name: GROUP_SEEDING_ENABLED
        value: 'False'
    database:
      name: rbac
    inMemoryDb: true

parameters:
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/rbac
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "false"
- description: ClowdEnv Name
  name: ENV_NAME
  requred: true
- description: Maximum amount of memory the Django container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Initial amount of cpu the Django container will request.
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 250m
- description: Maximum amount of cpu the Django container can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: 700m
- displayName: RBAC PSKs
  name: RBAC_PSKS
  value: rbac-psks
- displayName: Service Dependency Name
  name: SERVICE_DEPENDENCY_NAME
  value: rbac-pgsql
- displayName: API Prefix Path
  name: API_PATH_PREFIX
  value: /api/rbac
- displayName: Development
  name: DEVELOPMENT
  value: 'false'
- displayName: Rbac log level
  name: RBAC_LOG_LEVEL
  value: INFO
- displayName: Django log level
  name: DJANGO_LOG_LEVEL
  value: INFO
- displayName: Django log formatter
  name: DJANGO_LOG_FORMATTER
  value: simple
- displayName: Django log handlers
  name: DJANGO_LOG_HANDLERS
  value: console
- displayName: Django log directory
  name: DJANGO_LOG_DIRECTORY
  required: false
- displayName: Django logging file
  name: DJANGO_LOGGING_FILE
  required: false
- description: Name of the rbac-config config map
  name: CONFIG_MAP_NAME
  value: rbac-config
- description: Name of the predefined access permissions config map
  name: MODEL_ACCESS_PERMISSIONS
  value: model-access-permissions
- description: minimum number of pods to use when autoscaling is enabled
  name: MIN_REPLICAS
  value: '1'
- description: maximum number of pods to use when autoscaling is enabled
  name: MAX_REPLICAS
  value: '1'
- description: target CPU utilization for the service
  name: TARGET_CPU_UTILIZATION
  value: '90'
- description: 'Options can be found in the doc: https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS'
  displayName: Postgres SSL mode
  name: PGSSLMODE
  value: prefer
- description: Python boolean value to enable/disable permission seeding on app boot
  name: PERMISSION_SEEDING_ENABLED
  value: 'True'
- description: Python boolean value to enable/disable role seeding on app boot
  name: ROLE_SEEDING_ENABLED
  value: 'True'
- description: Python boolean value to enable/disable group seeding on app boot
  name: GROUP_SEEDING_ENABLED
  value: 'True'
- description: Flag to disable migrations
  name: DISABLE_MIGRATE
  value: 'True'
- description: Enable the RBAC access cache
  name: ACCESS_CACHE_ENABLED
  value: 'True'
- description: Bypass interaction with the BOP service
  name: BYPASS_BOP_VERIFICATION
  value: 'False'
- description: Application allow list for role creation in RBAC
  name: ROLE_CREATE_ALLOW_LIST
  value: cost-management,remediations,inventory,drift,policies,advisor,catalog,approval,vulnerability,compliance,automation-analytics,notifications
- description: Timestamp expiration allowance on destructive actions through the internal
    RBAC API
  name: RBAC_DESTRUCTIVE_ENABLED_UNTIL
  value: ''
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Name of DB secret
  name: DB_SECRET_NAME
  value: rbac-db
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: rbac
- description: Initial amount of CPU the Flower container will request.
  displayName: Celery scheduler CPU Resource Request
  name: CELERY_SCHEDULER_CPU_REQUEST
  required: true
  value: 100m
- description: Maximum amount of CPU the scheduler container can use.
  displayName: CPU Limit
  name: CELERY_SCHEDULER_CPU_LIMIT
  required: true
  value: 300m
- description: Initial amount of memory the scheduler container will request.
  displayName: Celery scheduler Memory Resource Request
  name: CELERY_SCHEDULER_MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory the scheduler container can use.
  displayName: Memory Limit
  name: CELERY_SCHEDULER_MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: rbac
- description: Initial amount of CPU the worker container will request.
  displayName: Celery worker CPU Resource Request
  name: CELERY_WORKER_CPU_REQUEST
  required: true
  value: 100m
- description: Maximum amount of CPU the worker container can use.
  displayName: CPU Limit
  name: CELERY_WORKER_CPU_LIMIT
  required: true
  value: 300m
- description: Initial amount of memory the worker container will request.
  displayName: Celery worker Memory Resource Request
  name: CELERY_WORKER_MEMORY_REQUEST
  required: true
  value: 256Mi
- description: Maximum amount of memory the worker container can use.
  displayName: Memory Limit
  name: CELERY_WORKER_MEMORY_LIMIT
  required: true
  value: 512Mi
- displayName: Django Debug
  name: DJANGO_DEBUG
  value: 'false'
- displayName: Django log level
  name: DJANGO_LOG_LEVEL
  value: INFO
- description: 'Options can be found in the doc: https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS'
  displayName: Postgres SSL mode
  name: PGSSLMODE
  value: prefer
- description: Name of the rbac-config config map
  name: CONFIG_MAP_NAME
  value: rbac-config
- description: Name of the predefined access permissions config map
  name: MODEL_ACCESS_PERMISSIONS
  value: model-access-permissions
- description: Name of DB secret
  name: DB_SECRET_NAME
  value: rbac-db
