apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: binding-scope-migration
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    labels:
      app: rbac
    name: binding-scope-migration-${RUN_NUMBER}
  spec:
    appName: rbac
    jobs:
      - binding-scope-migration
parameters:
- name: RUN_NUMBER
  description: Used to track and re-run the job
  value: '1'
