#
# Copyright 2019 Red Hat, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
"""
Django settings for rbac project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import datetime
import logging
import os
import ssl
import sys
from urllib.parse import quote as _url_quote

import pytz
import redis
from app_common_python import DependencyEndpoints, KafkaTopics, LoadedConfig
from boto3 import client as boto_client
from corsheaders.defaults import default_headers
from dateutil.parser import parse as parse_dt
from feature_flags import FEATURE_FLAGS

from . import database
from .env import ENVIRONMENT

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases


# Sentry monitoring configuration
# Note: Sentry is disabled unless it is explicitly turned on by setting DSN
# Note: Although we are using sentry-sdk we are connecting to Glitchtip DSN

GLITCHTIP_DSN = os.getenv("GLITCHTIP_DSN", "")
if GLITCHTIP_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.redis import RedisIntegration

    sentry_sdk.init(dsn=GLITCHTIP_DSN, integrations=[DjangoIntegration(), RedisIntegration()])
    print("Sentry SDK initialization using Glitchtip was successful!")
else:
    print("GLITCHTIP_DSN was not set, skipping Glitchtip initialization.")

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GIT_COMMIT = ENVIRONMENT.get_value("GIT_COMMIT", default="local-dev")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The SECRET_KEY is provided via an environment variable in OpenShift
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    # safe value used for development when DJANGO_SECRET_KEY might not be set
    "asvuhxowz)zjbo4%7pc$ek1nbfh_-#%$bq_x8tkh=#e24825=5",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default value: False
DEBUG = False if os.getenv("DJANGO_DEBUG", "False") == "False" else True  # pylint: disable=R1719

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    # django
    # 'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third-party
    "rest_framework",
    "django_filters",
    "corsheaders",
    "django_prometheus",
    "django_extensions",
    # local apps
    "api",
    "management",
]

SHARED_APPS = (
    "management",
    "api",
    "django.contrib.contenttypes",
    # 'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "rest_framework",
    "django_extensions",
)

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "rbac.middleware.DisableCSRF",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "rbac.middleware.IdentityHeaderMiddleware",
    "internal.middleware.InternalIdentityHeaderMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    "rbac.middleware.ReadOnlyApiMiddleware",
]

DEVELOPMENT = ENVIRONMENT.bool("DEVELOPMENT", default=False)
if DEVELOPMENT:
    MIDDLEWARE.insert(5, "rbac.dev_middleware.DevelopmentIdentityHeaderMiddleware")
# Don't try to go verify Principals against the BOP user service
BYPASS_BOP_VERIFICATION = ENVIRONMENT.bool("BYPASS_BOP_VERIFICATION", default=False)

AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.AllowAllUsersModelBackend"]


ROOT_URLCONF = "rbac.urls"

WSGI_APPLICATION = "rbac.wsgi.application"

DATABASES = {"default": database.config()}

PROMETHEUS_EXPORT_MIGRATIONS = False

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True


USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


API_PATH_PREFIX = os.getenv("API_PATH_PREFIX", "/")
STATIC_API_PATH_PREFIX = API_PATH_PREFIX
if STATIC_API_PATH_PREFIX != "" and (not STATIC_API_PATH_PREFIX.endswith("/")):
    STATIC_API_PATH_PREFIX = STATIC_API_PATH_PREFIX + "/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "{}/static/".format(API_PATH_PREFIX.rstrip("/"))

STATICFILES_DIRS = [os.path.join(BASE_DIR, "..", "docs/source/specs")]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

INTERNAL_IPS = ["127.0.0.1"]

DEFAULT_PAGINATION_CLASS = "api.common.pagination.StandardResultsSetPagination"
DEFAULT_EXCEPTION_HANDLER = "api.common.exception_handler.exception_version_handler"

# django rest_framework settings
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"],
    "DEFAULT_PAGINATION_CLASS": DEFAULT_PAGINATION_CLASS,
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "EXCEPTION_HANDLER": DEFAULT_EXCEPTION_HANDLER,
    "ORDERING_PARAM": "order_by",
}

# CW settings
if ENVIRONMENT.bool("CLOWDER_ENABLED", default=False):
    if ENVIRONMENT.bool("CW_NULL_WORKAROUND", default=True):
        CW_AWS_ACCESS_KEY_ID = None
        CW_AWS_SECRET_ACCESS_KEY = None
        CW_AWS_REGION = None
        CW_LOG_GROUP = None
    else:
        CW_AWS_ACCESS_KEY_ID = LoadedConfig.logging.cloudwatch.accessKeyId
        CW_AWS_SECRET_ACCESS_KEY = LoadedConfig.logging.cloudwatch.secretAccessKey
        CW_AWS_REGION = LoadedConfig.logging.cloudwatch.region
        CW_LOG_GROUP = LoadedConfig.logging.cloudwatch.logGroup
else:
    CW_AWS_ACCESS_KEY_ID = ENVIRONMENT.get_value("CW_AWS_ACCESS_KEY_ID", default=None)
    CW_AWS_SECRET_ACCESS_KEY = ENVIRONMENT.get_value("CW_AWS_SECRET_ACCESS_KEY", default=None)
    CW_AWS_REGION = ENVIRONMENT.get_value("CW_AWS_REGION", default="us-east-1")
    CW_LOG_GROUP = ENVIRONMENT.get_value("CW_LOG_GROUP", default="platform-dev")

CW_CREATE_LOG_GROUP = ENVIRONMENT.bool("CW_CREATE_LOG_GROUP", default=False)

LOGGING_FORMATTER = os.getenv("DJANGO_LOG_FORMATTER", "simple")
DJANGO_LOGGING_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO")
RBAC_LOGGING_LEVEL = os.getenv("RBAC_LOG_LEVEL", "INFO")


def _parse_logging_handlers(raw_value):
    """Parse comma-separated handler names, strip whitespace, and deduplicate.

    'console' and 'ecs' both write to stderr.  Having both produces duplicate
    log lines for every event.  When both are specified, keep only 'console'
    (plain text for pod stdout / ``oc logs``).  CloudWatch receives structured
    JSON via the separate watchtower handler, which always uses ecs_formatter.
    Use DJANGO_LOG_HANDLERS=ecs to force JSON on stdout (e.g. for local testing).
    """
    handlers = [h.strip() for h in raw_value.split(",") if h.strip()]
    if "console" in handlers and "ecs" in handlers:
        handlers = [h for h in handlers if h != "ecs"]
    return handlers


LOGGING_HANDLERS = _parse_logging_handlers(os.getenv("DJANGO_LOG_HANDLERS", "console"))

ENV_NAME = os.getenv("ENV_NAME", "stage")
VERBOSE_FORMATTING = (
    "%(levelname)s %(asctime)s [%(env_name)s]"
    " [req=%(request_id)s org=%(org_id)s user=%(user_id)s type=%(user_type)s]"
    " %(module)s %(process)d %(thread)d %(message)s"
)

if DEBUG and "ecs" in LOGGING_HANDLERS:
    DEBUG_LOG_HANDLERS = [v for v in LOGGING_HANDLERS if v != "ecs"]
    if DEBUG_LOG_HANDLERS == []:
        DEBUG_LOG_HANDLERS = ["console"]
else:
    DEBUG_LOG_HANDLERS = LOGGING_HANDLERS

LOG_DIRECTORY = os.getenv("LOG_DIRECTORY", BASE_DIR)
DEFAULT_LOG_FILE = os.path.join(LOG_DIRECTORY, "app.log")
LOGGING_FILE = os.getenv("DJANGO_LOG_FILE", DEFAULT_LOG_FILE)

if CW_AWS_ACCESS_KEY_ID:
    LOGGING_HANDLERS += ["watchtower"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "env_name": {"()": "rbac.logging_filters.EnvironmentFilter", "env_name": ENV_NAME},
        "request_context": {"()": "rbac.logging_filters.RequestContextFilter"},
    },
    "formatters": {
        "verbose": {"format": VERBOSE_FORMATTING},
        "simple": {
            "format": "[%(asctime)s] %(levelname)s [%(env_name)s]"
            " [req=%(request_id)s org=%(org_id)s user=%(user_id)s type=%(user_type)s]: %(message)s"
        },
        "ecs_formatter": {"()": "rbac.ECSCustom.ECSCustomFormatter"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": LOGGING_FORMATTER,
            "filters": ["env_name", "request_context"],
        },
        "file": {
            "level": RBAC_LOGGING_LEVEL,
            "class": "logging.FileHandler",
            "filename": LOGGING_FILE,
            "formatter": LOGGING_FORMATTER,
            "filters": ["env_name", "request_context"],
        },
        "ecs": {
            "class": "logging.StreamHandler",
            "formatter": "ecs_formatter",
            "filters": ["env_name", "request_context"],
        },
    },
    "loggers": {
        "django": {"handlers": LOGGING_HANDLERS, "level": DJANGO_LOGGING_LEVEL, "propagate": False},
        "django.server": {"handlers": DEBUG_LOG_HANDLERS, "level": DJANGO_LOGGING_LEVEL, "propagate": False},
        "django.request": {"handlers": DEBUG_LOG_HANDLERS, "level": DJANGO_LOGGING_LEVEL, "propagate": False},
        "api": {"handlers": LOGGING_HANDLERS, "level": RBAC_LOGGING_LEVEL, "propagate": False},
        "internal": {"handlers": LOGGING_HANDLERS, "level": RBAC_LOGGING_LEVEL, "propagate": False},
        "rbac": {"handlers": LOGGING_HANDLERS, "level": RBAC_LOGGING_LEVEL, "propagate": False},
        "management": {"handlers": LOGGING_HANDLERS, "level": RBAC_LOGGING_LEVEL, "propagate": False},
        "core": {"handlers": LOGGING_HANDLERS, "level": RBAC_LOGGING_LEVEL, "propagate": False},
        "migration_tool": {"handlers": LOGGING_HANDLERS, "level": RBAC_LOGGING_LEVEL, "propagate": False},
        "feature_flags": {"handlers": DEBUG_LOG_HANDLERS, "level": "DEBUG", "propagate": False},
    },
    # Attach default handlers to root so that loggers without explicit
    # handlers still have a fallback output instead of silently dropping records.
    "root": {"handlers": LOGGING_HANDLERS, "level": "WARNING"},
}

if CW_AWS_ACCESS_KEY_ID:
    NAMESPACE = ENVIRONMENT.get_value("APP_NAMESPACE", default="unknown")
    # Allow different components (e.g., kafka-consumer) to use distinct CloudWatch log streams
    # by appending a suffix to the namespace-based stream name
    CW_STREAM_NAME_SUFFIX = ENVIRONMENT.get_value("CW_STREAM_NAME_SUFFIX", default="")
    CW_STREAM_NAME = f"{NAMESPACE}{CW_STREAM_NAME_SUFFIX}" if CW_STREAM_NAME_SUFFIX else NAMESPACE

    boto3_logs_client = boto_client(
        "logs",
        region_name=CW_AWS_REGION,
        aws_access_key_id=CW_AWS_ACCESS_KEY_ID,
        aws_secret_access_key=CW_AWS_SECRET_ACCESS_KEY,
    )

    # Formatter is hardcoded to ecs_formatter so CloudWatch always receives
    # structured JSON, regardless of the DJANGO_LOG_FORMATTER env var which
    # only controls the stdout/console handler format.
    WATCHTOWER_HANDLER = {
        "level": RBAC_LOGGING_LEVEL,
        "class": "watchtower.CloudWatchLogHandler",
        "boto3_client": boto3_logs_client,
        "log_group_name": CW_LOG_GROUP,
        "stream_name": CW_STREAM_NAME,
        "formatter": "ecs_formatter",
        "use_queues": True,
        "create_log_group": CW_CREATE_LOG_GROUP,
        "filters": ["env_name", "request_context"],
    }
    LOGGING["handlers"]["watchtower"] = WATCHTOWER_HANDLER

# Cors Setup
# See https://github.com/ottoyiu/django-cors-headers
CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_HEADERS = default_headers + ("x-rh-identity", "HTTP_X_RH_IDENTITY")
CORS_EXPOSE_HEADERS = list(globals().get("CORS_EXPOSE_HEADERS", [])) + ["Mcp-Session-Id"]

APPEND_SLASH = False

# Celery settings
REDIS_USERNAME = None
REDIS_SSL_CA_CERTS = None
if ENVIRONMENT.bool("CLOWDER_ENABLED", default=False):
    REDIS_HOST = LoadedConfig.inMemoryDb.hostname
    REDIS_PORT = LoadedConfig.inMemoryDb.port
    REDIS_PASSWORD = LoadedConfig.inMemoryDb.password
    REDIS_SSL = REDIS_PASSWORD is not None
else:
    REDIS_HOST = ENVIRONMENT.get_value("REDIS_HOST", default="localhost")
    REDIS_PORT = ENVIRONMENT.get_value("REDIS_PORT", default="6379")
    REDIS_PASSWORD = ENVIRONMENT.get_value("REDIS_PASSWORD", default=None)
    REDIS_USERNAME = ENVIRONMENT.get_value("REDIS_USERNAME", default=None)
    REDIS_SSL_CA_CERTS = ENVIRONMENT.get_value("REDIS_SSL_CA_CERTS", default=None)
    REDIS_SSL = ENVIRONMENT.bool("REDIS_SSL", default=False)

# Feature Flag settings
FEATURE_FLAGS_CONF = LoadedConfig.featureFlags
if ENVIRONMENT.bool("CLOWDER_ENABLED", default=False) and FEATURE_FLAGS_CONF:
    FEATURE_FLAGS_TOKEN = FEATURE_FLAGS_CONF.clientAccessToken
    FEATURE_FLAGS_URL = (
        f"{FEATURE_FLAGS_CONF.scheme.value}://{FEATURE_FLAGS_CONF.hostname}:{FEATURE_FLAGS_CONF.port}/api"
    )
    APP_NAME = LoadedConfig.metadata.name
else:
    FEATURE_FLAGS_TOKEN = ENVIRONMENT.get_value("FEATURE_FLAGS_TOKEN", default=None)
    FEATURE_FLAGS_URL = ENVIRONMENT.get_value("FEATURE_FLAGS_URL", default="http://localhost:4242/api")
    APP_NAME = "rbac"

CLOWDER_ENABLED = ENVIRONMENT.bool("CLOWDER_ENABLED", default=False)

FEATURE_FLAGS_CACHE_DIR = ENVIRONMENT.get_value("FEATURE_FLAGS_CACHE_DIR", default="/tmp/")
UNLEASH_REFRESH_INTERVAL = ENVIRONMENT.int("UNLEASH_REFRESH_INTERVAL", default=30)
UNLEASH_REQUEST_TIMEOUT = ENVIRONMENT.int("UNLEASH_REQUEST_TIMEOUT", default=30)

ACCESS_CACHE_DB = 1
ACCESS_CACHE_LIFETIME = 10 * 60
ACCESS_CACHE_ENABLED = ENVIRONMENT.bool("ACCESS_CACHE_ENABLED", default=True)
ACCESS_CACHE_CONNECT_SIGNALS = ENVIRONMENT.bool("ACCESS_CACHE_CONNECT_SIGNALS", default=True)

REDIS_MAX_CONNECTIONS = ENVIRONMENT.get_value("REDIS_MAX_CONNECTIONS", default=10)
REDIS_SOCKET_CONNECT_TIMEOUT = ENVIRONMENT.get_value("REDIS_SOCKET_CONNECT_TIMEOUT", default=0.1)
REDIS_SOCKET_TIMEOUT = ENVIRONMENT.get_value("REDIS_SOCKET_TIMEOUT", default=0.1)
REDIS_CACHE_CONNECTION_PARAMS = dict(
    max_connections=REDIS_MAX_CONNECTIONS,
    host=REDIS_HOST,
    port=REDIS_PORT,
    db=ACCESS_CACHE_DB,
    socket_connect_timeout=REDIS_SOCKET_CONNECT_TIMEOUT,
    socket_timeout=REDIS_SOCKET_TIMEOUT,
)

if REDIS_PASSWORD:
    REDIS_CACHE_CONNECTION_PARAMS["password"] = REDIS_PASSWORD
if REDIS_USERNAME:
    REDIS_CACHE_CONNECTION_PARAMS["username"] = REDIS_USERNAME
if REDIS_SSL:
    REDIS_CACHE_CONNECTION_PARAMS["connection_class"] = redis.SSLConnection
    REDIS_SSL_CERT_REQS = ssl.CERT_REQUIRED if REDIS_SSL_CA_CERTS else ssl.CERT_NONE
    REDIS_CACHE_CONNECTION_PARAMS["ssl_cert_reqs"] = REDIS_SSL_CERT_REQS
    if REDIS_SSL_CA_CERTS:
        REDIS_CACHE_CONNECTION_PARAMS["ssl_ca_certs"] = REDIS_SSL_CA_CERTS

_redis_scheme = "rediss" if REDIS_SSL else "redis"
if REDIS_USERNAME and REDIS_PASSWORD:
    _redis_auth = f"{_url_quote(REDIS_USERNAME)}:{_url_quote(REDIS_PASSWORD)}@"
elif REDIS_PASSWORD:
    _redis_auth = f":{_url_quote(REDIS_PASSWORD)}@"
else:
    _redis_auth = ""
DEFAULT_REDIS_URL = f"{_redis_scheme}://{_redis_auth}{REDIS_HOST}:{REDIS_PORT}/0"
DJANGO_CACHE_URL = f"{_redis_scheme}://{_redis_auth}{REDIS_HOST}:{REDIS_PORT}/2"

_cache_location = ENVIRONMENT.get_value("DJANGO_CACHE_BACKEND", default=DJANGO_CACHE_URL)
if _cache_location.startswith("locmem"):
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}
else:
    _cache_config: dict = {"BACKEND": "django.core.cache.backends.redis.RedisCache", "LOCATION": _cache_location}
    if REDIS_SSL:
        _cache_options: dict = {"ssl_cert_reqs": REDIS_SSL_CERT_REQS}
        if REDIS_SSL_CA_CERTS:
            _cache_options["ssl_ca_certs"] = REDIS_SSL_CA_CERTS
        _cache_config["OPTIONS"] = _cache_options
    CACHES = {"default": _cache_config}

CELERY_BROKER_URL = ENVIRONMENT.get_value("CELERY_BROKER_URL", default=DEFAULT_REDIS_URL)
_celery_concurrency = ENVIRONMENT.int("CELERY_WORKER_CONCURRENCY", default=0)
if _celery_concurrency > 0:
    CELERY_WORKER_CONCURRENCY = _celery_concurrency

if REDIS_SSL:
    _celery_ssl_conf = {"ssl_cert_reqs": REDIS_SSL_CERT_REQS}
    if REDIS_SSL_CA_CERTS:
        _celery_ssl_conf["ssl_ca_certs"] = REDIS_SSL_CA_CERTS
    CELERY_BROKER_USE_SSL = _celery_ssl_conf
    CELERY_REDIS_BACKEND_USE_SSL = _celery_ssl_conf

ROLE_CREATE_ALLOW_LIST = ENVIRONMENT.get_value("ROLE_CREATE_ALLOW_LIST", default="").split(",")

# Dual write migration configuration
REPLICATION_TO_RELATION_ENABLED = ENVIRONMENT.bool("REPLICATION_TO_RELATION_ENABLED", default=False)
EPH_ENV = ENVIRONMENT.bool("EPH_ENV", default=False)
V2_MIGRATION_APP_EXCLUDE_LIST = [
    app.strip() for app in ENVIRONMENT.get_value("V2_MIGRATION_APP_EXCLUDE_LIST", default="").split(",") if app.strip()
]
V2_BOOTSTRAP_TENANT = ENVIRONMENT.bool("V2_BOOTSTRAP_TENANT", default=False)

# Migration Setup
TENANT_PARALLEL_MIGRATION_MAX_PROCESSES = ENVIRONMENT.int("TENANT_PARALLEL_MIGRATION_MAX_PROCESSES", default=2)
TENANT_PARALLEL_MIGRATION_CHUNKS = ENVIRONMENT.int("TENANT_PARALLEL_MIGRATION_CHUNKS", default=2)

# Seeding Setup
PERMISSION_SEEDING_ENABLED = ENVIRONMENT.bool("PERMISSION_SEEDING_ENABLED", default=True)
ROLE_SEEDING_ENABLED = ENVIRONMENT.bool("ROLE_SEEDING_ENABLED", default=True)
GROUP_SEEDING_ENABLED = ENVIRONMENT.bool("GROUP_SEEDING_ENABLED", default=True)
MAX_SEED_THREADS = ENVIRONMENT.int("MAX_SEED_THREADS", default=None)

try:
    DESTRUCTIVE_SEEDING_OK_UNTIL = parse_dt(
        os.environ.get("RBAC_DESTRUCTIVE_SEEDING_ENABLED_UNTIL", "not-a-real-time")
    )
    if DESTRUCTIVE_SEEDING_OK_UNTIL.tzinfo is None:
        DESTRUCTIVE_SEEDING_OK_UNTIL = DESTRUCTIVE_SEEDING_OK_UNTIL.replace(tzinfo=pytz.UTC)
except ValueError as e:
    DESTRUCTIVE_SEEDING_OK_UNTIL = datetime.datetime(1970, 1, 1, tzinfo=pytz.UTC)

# disable log messages less than CRITICAL when running unit tests.
if len(sys.argv) > 1 and sys.argv[1] == "test" and not ENVIRONMENT.bool("LOG_TEST_OUTPUT", default=False):
    logging.disable(logging.CRITICAL)

# Optionally log all DB queries
if ENVIRONMENT.bool("LOG_DATABASE_QUERIES", default=False):
    LOGGING["loggers"]["django.db.backends"] = {"handlers": ["console"], "level": "DEBUG", "propagate": False}

# Internal API Configuration
INTERNAL_API_PATH_PREFIXES = ["/_private/"]
A2S_PATH_PREFIX = "/_private/_a2s/"

try:
    INTERNAL_DESTRUCTIVE_API_OK_UNTIL = parse_dt(
        os.environ.get("RBAC_DESTRUCTIVE_API_ENABLED_UNTIL", "not-a-real-time")
    )
    if INTERNAL_DESTRUCTIVE_API_OK_UNTIL.tzinfo is None:
        INTERNAL_DESTRUCTIVE_API_OK_UNTIL = INTERNAL_DESTRUCTIVE_API_OK_UNTIL.replace(tzinfo=pytz.UTC)
except ValueError as e:
    INTERNAL_DESTRUCTIVE_API_OK_UNTIL = datetime.datetime(1970, 1, 1, tzinfo=pytz.UTC)

KAFKA_ENABLED = ENVIRONMENT.get_value("KAFKA_ENABLED", default=False)
MOCK_KAFKA = ENVIRONMENT.get_value("MOCK_KAFKA", default=False)
MOCK_REDIS = ENVIRONMENT.get_value("MOCK_REDIS", default=False)

NOTIFICATIONS_ENABLED = ENVIRONMENT.get_value("NOTIFICATIONS_ENABLED", default=False)
NOTIFICATIONS_RH_ENABLED = ENVIRONMENT.get_value("NOTIFICATIONS_RH_ENABLED", default=False)
NOTIFICATIONS_TOPIC = ENVIRONMENT.get_value("NOTIFICATIONS_TOPIC", default=None)

EXTERNAL_SYNC_TOPIC = ENVIRONMENT.get_value("EXTERNAL_SYNC_TOPIC", default=None)
EXTERNAL_CHROME_TOPIC = ENVIRONMENT.get_value("EXTERNAL_CHROME_TOPIC", default=None)

RBAC_KAFKA_CONSUMER_TOPIC = ENVIRONMENT.get_value("RBAC_KAFKA_CONSUMER_TOPIC", default=None)

RBAC_KAFKA_CONSUMER_GROUP_ID = ENVIRONMENT.get_value("RBAC_KAFKA_CONSUMER_GROUP_ID", default="rbac-consumer-group")

RBAC_KAFKA_CUSTOM_CONSUMER_BROKER = ENVIRONMENT.get_value("RBAC_KAFKA_CUSTOM_CONSUMER_BROKER", default="")

KAFKA_PRINCIPAL_CLEANUP_TOPIC = ENVIRONMENT.get_value("KAFKA_PRINCIPAL_CLEANUP_TOPIC", default="")
KAFKA_PRINCIPAL_CLEANUP_DLQ_TOPIC = ENVIRONMENT.get_value("KAFKA_PRINCIPAL_CLEANUP_DLQ_TOPIC", default="")

# if we don't enable KAFKA we can't use the notifications
if not KAFKA_ENABLED:
    NOTIFICATIONS_ENABLED = False
    NOTIFICATIONS_RH_ENABLED = False
    NOTIFICATIONS_TOPIC = None

# Kafka settings
KAFKA_SERVERS = []

if KAFKA_ENABLED:
    KAFKA_AUTH = {}
    if ENVIRONMENT.bool("CLOWDER_ENABLED", default=False):
        kafka_brokers = LoadedConfig.kafka.brokers
        broker_index = 0
        if not kafka_brokers:
            raise ValueError("No kafka brokers available")
        for broker in kafka_brokers:
            if broker and broker.hostname != None and broker.port != None:
                kafka_host = broker.hostname
                kafka_port = broker.port
                kafka_info = f"{kafka_host}:{kafka_port}"
                KAFKA_SERVERS.append(kafka_info)

                if broker.authtype != None and broker.authtype.value == "sasl":
                    broker_index = kafka_brokers.index(broker)
            else:
                raise ValueError("Broker value is none. It does not contain hostname, port, or authtype")
        try:
            if kafka_brokers[broker_index].authtype.value == "sasl":
                KAFKA_AUTH.update(
                    {
                        "bootstrap_servers": KAFKA_SERVERS,
                        "sasl_plain_username": kafka_brokers[broker_index].sasl.username,
                        "sasl_plain_password": kafka_brokers[broker_index].sasl.password,
                        "sasl_mechanism": kafka_brokers[broker_index].sasl.saslMechanism.upper(),
                        "security_protocol": kafka_brokers[broker_index].sasl.securityProtocol.upper(),
                        "retries": 5,
                    }
                )
            if kafka_brokers[broker_index].cacert:
                KAFKA_AUTH["ssl_cafile"] = LoadedConfig.kafka_ca()
        except AttributeError:
            KAFKA_AUTH = {}
    else:
        kafka_host = "localhost"
        kafka_port = "9092"
        kafka_info = f"{kafka_host}:{kafka_port}"
        KAFKA_SERVERS.append(kafka_info)

    clowder_notifications_topic = KafkaTopics.get(NOTIFICATIONS_TOPIC)
    if clowder_notifications_topic:
        NOTIFICATIONS_TOPIC = clowder_notifications_topic.name

    clowder_sync_topic = KafkaTopics.get(EXTERNAL_SYNC_TOPIC)
    if clowder_sync_topic:
        EXTERNAL_SYNC_TOPIC = clowder_sync_topic.name

    clowder_chrome_topic = KafkaTopics.get(EXTERNAL_CHROME_TOPIC)
    if clowder_chrome_topic:
        EXTERNAL_CHROME_TOPIC = clowder_chrome_topic.name

    clowder_rbac_consumer_topic = KafkaTopics.get(RBAC_KAFKA_CONSUMER_TOPIC)
    if clowder_rbac_consumer_topic:
        RBAC_KAFKA_CONSUMER_TOPIC = clowder_rbac_consumer_topic.name

    clowder_principal_cleanup_topic = KafkaTopics.get(KAFKA_PRINCIPAL_CLEANUP_TOPIC)
    if clowder_principal_cleanup_topic:
        KAFKA_PRINCIPAL_CLEANUP_TOPIC = clowder_principal_cleanup_topic.name

    clowder_principal_cleanup_dlq_topic = KafkaTopics.get(KAFKA_PRINCIPAL_CLEANUP_DLQ_TOPIC)
    if clowder_principal_cleanup_dlq_topic:
        KAFKA_PRINCIPAL_CLEANUP_DLQ_TOPIC = clowder_principal_cleanup_dlq_topic.name


IT_KAFKA_BOOTSTRAP_SERVERS = ENVIRONMENT.get_value("IT_KAFKA_BOOTSTRAP_SERVERS", default="")
IT_KAFKA_USERNAME = ENVIRONMENT.get_value("IT_KAFKA_USERNAME", default="")
IT_KAFKA_PASSWORD = ENVIRONMENT.get_value("IT_KAFKA_PASSWORD", default="")
IT_KAFKA_SASL_MECHANISM = ENVIRONMENT.get_value("IT_KAFKA_SASL_MECHANISM", default="SCRAM-SHA-512")
IT_KAFKA_SECURITY_PROTOCOL = ENVIRONMENT.get_value("IT_KAFKA_SECURITY_PROTOCOL", default="SASL_SSL")

IT_KAFKA_SERVERS = [server.strip() for server in IT_KAFKA_BOOTSTRAP_SERVERS.split(",") if server.strip()]
IT_KAFKA_AUTH = {}
if IT_KAFKA_SERVERS and IT_KAFKA_USERNAME and IT_KAFKA_PASSWORD:
    IT_KAFKA_AUTH = {
        "bootstrap_servers": IT_KAFKA_SERVERS,
        "sasl_plain_username": IT_KAFKA_USERNAME,
        "sasl_plain_password": IT_KAFKA_PASSWORD,
        "sasl_mechanism": IT_KAFKA_SASL_MECHANISM.upper(),
        "security_protocol": IT_KAFKA_SECURITY_PROTOCOL.upper(),
        "retries": 5,  # producer-only; PRODUCER_ONLY_CONFIGS strips it for consumers
    }

KAFKA_CLUSTERS = {
    "it_managed": {"servers": IT_KAFKA_SERVERS, "auth": IT_KAFKA_AUTH},
}

# BOP TLS settings
if ENVIRONMENT.bool("CLOWDER_ENABLED", default=False) and ENVIRONMENT.bool("USE_CLOWDER_CA_FOR_BOP", default=False):
    BOP_CLIENT_CERT_PATH = LoadedConfig.tlsCAPath
else:
    BOP_CLIENT_CERT_PATH = os.path.join(BASE_DIR, "management", "principal", "certs", "client.pem")

# IT settings for the service accounts fetching.
IT_BYPASS_PERMISSIONS_MODIFY_SERVICE_ACCOUNTS = ENVIRONMENT.bool(
    "IT_BYPASS_PERMISSIONS_MODIFY_SERVICE_ACCOUNTS", default=False
)
IT_BYPASS_IT_CALLS = ENVIRONMENT.bool("IT_BYPASS_IT_CALLS", default=False)
IT_BYPASS_TOKEN_VALIDATION = ENVIRONMENT.bool("IT_BYPASS_TOKEN_VALIDATION", default=False)
IT_BYPASS_SYSTEM_USER_ID = ENVIRONMENT.get_value(
    "IT_BYPASS_SYSTEM_USER_ID", default="mocked-user-id-because-token-validation-is-disabled"
)
IT_SERVICE_BASE_PATH = ENVIRONMENT.get_value("IT_SERVICE_BASE_PATH", default="/auth/realms/redhat-external/apis")
IT_SERVICE_HOST = ENVIRONMENT.get_value("IT_SERVICE_HOST", default="localhost")
IT_SERVICE_PORT = ENVIRONMENT.int("IT_SERVICE_PORT", default="443")
IT_SERVICE_PROTOCOL_SCHEME = ENVIRONMENT.get_value("IT_SERVICE_PROTOCOL_SCHEME", default="https")
IT_SERVICE_REALM = ENVIRONMENT.get_value("IT_SERVICE_REALM", default="/auth/realms/redhat-external")
IT_SERVICE_TIMEOUT_SECONDS = ENVIRONMENT.int("IT_SERVICE_TIMEOUT_SECONDS", default=10)
IT_TOKEN_JKWS_CACHE_LIFETIME = ENVIRONMENT.int("IT_TOKEN_JKWS_CACHE_LIFETIME", default=28800)

PRINCIPAL_USER_DOMAIN = ENVIRONMENT.get_value("PRINCIPAL_USER_DOMAIN", default="localhost")

# Settings for enabling/disabling deletion in principal cleanup job via UMB
PRINCIPAL_CLEANUP_DELETION_ENABLED_UMB = ENVIRONMENT.bool("PRINCIPAL_CLEANUP_DELETION_ENABLED_UMB", default=False)
PRINCIPAL_CLEANUP_UPDATE_ENABLED_UMB = ENVIRONMENT.bool("PRINCIPAL_CLEANUP_UPDATE_ENABLED_UMB", default=False)
UMB_JOB_ENABLED = ENVIRONMENT.bool("UMB_JOB_ENABLED", default=True)

UMB_HOST = ENVIRONMENT.get_value("UMB_HOST", default="localhost")
UMB_PORT = ENVIRONMENT.get_value("UMB_PORT", default="61612")

# Settings for enabling/disabling deletion in principal cleanup job via Kafka
PRINCIPAL_CLEANUP_DELETION_ENABLED_KAFKA = ENVIRONMENT.bool("PRINCIPAL_CLEANUP_DELETION_ENABLED_KAFKA", default=False)
PRINCIPAL_CLEANUP_UPDATE_ENABLED_KAFKA = ENVIRONMENT.bool("PRINCIPAL_CLEANUP_UPDATE_ENABLED_KAFKA", default=False)
KAFKA_PRINCIPAL_CLEANUP_JOB_ENABLED = ENVIRONMENT.bool("KAFKA_PRINCIPAL_CLEANUP_JOB_ENABLED", default=True)

# Validate Kafka principal cleanup configuration at startup
# Fail fast if Kafka cleanup is enabled but topic is not configured
if PRINCIPAL_CLEANUP_DELETION_ENABLED_KAFKA and not KAFKA_PRINCIPAL_CLEANUP_TOPIC:
    raise ValueError(
        "PRINCIPAL_CLEANUP_DELETION_ENABLED_KAFKA is True but KAFKA_PRINCIPAL_CLEANUP_TOPIC is not configured. "
        "Set KAFKA_PRINCIPAL_CLEANUP_TOPIC to a valid Kafka topic name or disable Kafka cleanup."
    )

# Service account name
SA_NAME = ENVIRONMENT.get_value("SA_NAME", default="nonprod-hcc-rbac")

REDHAT_SSO = ENVIRONMENT.get_value("REDHAT_SSO", default="")
OPENID_URL = ENVIRONMENT.get_value("OPENID_URL", default="/auth/realms/redhat-external/protocol/openid-connect/token")
SCOPE = ENVIRONMENT.get_value("SCOPE", default="openid")
TOKEN_GRANT_TYPE = ENVIRONMENT.get_value("TOKEN_GRANT_TYPE", default="client_credentials")
RELATION_API_SERVER = ENVIRONMENT.get_value("RELATION_API_SERVER", default="localhost:9000")
KESSEL_RELATION_CLOWDER_APPLICATION_NAME = "kessel-relations"

if ENVIRONMENT.bool("CLOWDER_ENABLED", default=False):
    try:
        hostname = DependencyEndpoints[KESSEL_RELATION_CLOWDER_APPLICATION_NAME]["api"].hostname
        RELATION_API_SERVER = f"{hostname}:9000"
    except KeyError as e:
        # Note: Can't use logging here as it runs before Django logging config is applied
        print(
            f"WARNING: Dependency endpoint for '{KESSEL_RELATION_CLOWDER_APPLICATION_NAME}' not found: {e}. "
            f"Falling back to default RELATION_API_SERVER value: {RELATION_API_SERVER}"
        )

INVENTORY_API_CLIENT_ID = ENVIRONMENT.get_value("INVENTORY_API_CLIENT_ID", default="")
INVENTORY_API_CLIENT_SECRET = ENVIRONMENT.get_value("INVENTORY_API_CLIENT_SECRET", default="")
INVENTORY_API_TOKEN_URL = ENVIRONMENT.get_value(
    "INVENTORY_API_TOKEN_URL",
    default="https://sso.stage.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token",
)
INVENTORY_API_LOCAL = ENVIRONMENT.bool("INVENTORY_API_LOCAL", default=True)
INVENTORY_API_SERVER = ENVIRONMENT.get_value("INVENTORY_API_SERVER", default="localhost:9000")
KESSEL_INVENTORY_CLOWDER_APPLICATION_NAME = "kessel-inventory"
INVENTORY_API_PORT = 9000
if CLOWDER_ENABLED:
    try:
        hostname = DependencyEndpoints[KESSEL_INVENTORY_CLOWDER_APPLICATION_NAME]["api"].hostname
        INVENTORY_API_SERVER = f"{hostname}:{INVENTORY_API_PORT}"
    except KeyError as e:
        # Note: Can't use logging here as it runs before Django logging config is applied
        print(
            f"WARNING: Dependency endpoint for '{KESSEL_INVENTORY_CLOWDER_APPLICATION_NAME}' not found: {e}. "
            f"Falling back to default INVENTORY_API_SERVER value: {INVENTORY_API_SERVER}"
        )

# Versioned API settings
V2_APIS_ENABLED = ENVIRONMENT.bool("V2_APIS_ENABLED", default=False)
V2_READ_ONLY_API_MODE = ENVIRONMENT.bool("V2_READ_ONLY_API_MODE", default=False)
WORKSPACE_ACCESS_CHECK_V2_ENABLED = ENVIRONMENT.bool("WORKSPACE_ACCESS_CHECK_V2_ENABLED", default=False)
# When True, use 'role_binding_view' permission; when False, use 'view' permission for role binding access
USE_ROLE_BINDING_VIEW_PERMISSION = ENVIRONMENT.bool("USE_ROLE_BINDING_VIEW_PERMISSION", default=True)
# When True, tenant-level role binding access checks use Kessel instead of org-admin middleware
KESSEL_TENANT_AUTH_ENABLED = ENVIRONMENT.bool("KESSEL_TENANT_AUTH_ENABLED", default=False)
READ_ONLY_API_MODE = ENVIRONMENT.get_value("READ_ONLY_API_MODE", default=False)
V2_EDIT_API_ENABLED = ENVIRONMENT.bool("V2_EDIT_API_ENABLED", default=False)
V2_STRICT_ACCESS_CHECK_FLAG_APPLICATION_NAMES = [
    app.strip()
    for app in ENVIRONMENT.get_value("V2_STRICT_ACCESS_CHECK_FLAG_APPLICATION_NAMES", default="").split(",")
    if app.strip()
]
V1_ROLE_PERMISSION_BLOCK_LIST = [
    permission.strip()
    for permission in ENVIRONMENT.get_value("V1_ROLE_PERMISSION_BLOCK_LIST", default="").split(",")
    if permission.strip()
]

# Read-your-writes settings
READ_YOUR_WRITES_WORKSPACE_ENABLED = ENVIRONMENT.bool("READ_YOUR_WRITES_WORKSPACE_ENABLED", default=False)
READ_YOUR_WRITES_CHANNEL = ENVIRONMENT.get_value("READ_YOUR_WRITES_CHANNEL", default="READ_YOUR_WRITES_CHANNEL")
READ_YOUR_WRITES_TIMEOUT_SECONDS = ENVIRONMENT.int("READ_YOUR_WRITES_TIMEOUT_SECONDS", default=10)

# Workspace settings
WORKSPACE_APPLICATION_NAME = ENVIRONMENT.get_value("WORKSPACE_APPLICATION_NAME", default="inventory")
# Comma-separated list of resource types that should trigger workspace hierarchy
WORKSPACE_RESOURCE_TYPE = [
    t.strip() for t in ENVIRONMENT.get_value("WORKSPACE_RESOURCE_TYPE", default="groups,hosts,*").split(",")
]
WORKSPACE_ATTRIBUTE_FILTER = ENVIRONMENT.get_value("WORKSPACE_ATTRIBUTE_FILTER", default="group.id")
WORKSPACE_HIERARCHY_ENABLED = ENVIRONMENT.bool("WORKSPACE_HIERARCHY_ENABLED", False)
WORKSPACE_ORG_CREATION_LIMIT = ENVIRONMENT.get_value("WORKSPACE_ORG_CREATION_LIMIT", default=3000)
WORKSPACE_HIERARCHY_DEPTH_LIMIT = ENVIRONMENT.int("WORKSPACE_HIERARCHY_DEPTH_LIMIT", default=5)
WORKSPACE_RESTRICT_DEFAULT_PEERS = ENVIRONMENT.bool("WORKSPACE_RESTRICT_DEFAULT_PEERS", default=False)
# Enable detailed timing logs for v2 workspace access checks (for performance investigation)
WORKSPACE_ACCESS_TIMING_ENABLED = ENVIRONMENT.bool("WORKSPACE_ACCESS_TIMING_ENABLED", default=False)

# Permission scope configuration used by management.permission.scope_service.ImplicitResourceService.
# These can include wildcard patterns (e.g. "rbac:*:read" or "advisor:*:*").
ROOT_SCOPE_PERMISSIONS = ENVIRONMENT.get_value("ROOT_SCOPE_PERMISSIONS", default="")
TENANT_SCOPE_PERMISSIONS = ENVIRONMENT.get_value("TENANT_SCOPE_PERMISSIONS", default="")
DEFAULT_SCOPE_PERMISSIONS = ENVIRONMENT.get_value("DEFAULT_SCOPE_PERMISSIONS", default="")

# Whether to enable automatic scope migration during seeding. (This is intended to allow the migrations to be run
# manually before enabling the automatic runs, thus preventing the migration running sequentially for all roles on the
# first seeding run after the feature is added.)
AUTOMATIC_SCOPE_MIGRATION_ENABLED = ENVIRONMENT.bool("AUTOMATIC_SCOPE_MIGRATION_ENABLED", default=False)

# Parity check settings - background job for comparing RBAC access with Kessel PDP
PARITY_CHECK_ENABLED = ENVIRONMENT.bool("PARITY_CHECK_ENABLED", default=False)
PARITY_CHECK_INTERVAL_SECONDS = ENVIRONMENT.int("PARITY_CHECK_INTERVAL_SECONDS", default=300)
PARITY_CHECK_TENANT_SAMPLE_SIZE = ENVIRONMENT.int("PARITY_CHECK_TENANT_SAMPLE_SIZE", default=10)
PARITY_CHECK_PRINCIPAL_SAMPLE_SIZE = ENVIRONMENT.int("PARITY_CHECK_PRINCIPAL_SAMPLE_SIZE", default=50)
PARITY_CHECK_ORG_IDS = ENVIRONMENT.str("PARITY_CHECK_ORG_IDS", default="")
PARITY_CHECK_SCHEDULE = ENVIRONMENT.str("PARITY_CHECK_SCHEDULE", default="0 0 * * *")

# Disaster recovery settings
DR_RELATIONS_RECONCILE_ENABLED = ENVIRONMENT.bool("DR_RELATIONS_RECONCILE_ENABLED", default=False)
DR_KAFKA_CONSUMER_GROUP_ID = ENVIRONMENT.get_value("DR_KAFKA_CONSUMER_GROUP_ID", default="rbac-dr-consumer-group")
DR_MAX_EVENTS_PER_RECONCILE = ENVIRONMENT.int("DR_MAX_EVENTS_PER_RECONCILE", default=10000)
DR_SKIP_EVENT_TYPES = [
    t.strip()
    for t in ENVIRONMENT.get_value(
        "DR_SKIP_EVENT_TYPES",
        default="",
    ).split(",")
    if t.strip()
]

# Org level permissons parent role uuids
SYSTEM_DEFAULT_ROOT_WORKSPACE_ROLE_UUID = ENVIRONMENT.get_value("SYSTEM_DEFAULT_ROOT_WORKSPACE_ROLE_UUID", default="")
SYSTEM_DEFAULT_TENANT_ROLE_UUID = ENVIRONMENT.get_value("SYSTEM_DEFAULT_TENANT_ROLE_UUID", default="")
SYSTEM_ADMIN_ROOT_WORKSPACE_ROLE_UUID = ENVIRONMENT.get_value("SYSTEM_ADMIN_ROOT_WORKSPACE_ROLE_UUID", default="")
SYSTEM_ADMIN_TENANT_ROLE_UUID = ENVIRONMENT.get_value("SYSTEM_ADMIN_TENANT_ROLE_UUID", default="")

# MCP settings
MCP_ENABLED = ENVIRONMENT.bool("MCP_ENABLED", default=True)
MCP_TOOL_TIMEOUT_SECONDS = ENVIRONMENT.int("MCP_TOOL_TIMEOUT_SECONDS", default=30)
MCP_TOOL_MAX_WORKERS = ENVIRONMENT.int("MCP_TOOL_MAX_WORKERS", default=10)
MCP_SHUTDOWN_TIMEOUT_SECONDS = ENVIRONMENT.int("MCP_SHUTDOWN_TIMEOUT_SECONDS", default=60)
MCP_WRITE_ENABLED = ENVIRONMENT.bool("MCP_WRITE_ENABLED", default=False)
MCP_WRITE_CONFIRMATION = ENVIRONMENT.bool("MCP_WRITE_CONFIRMATION", default=True)
MCP_WRITE_CONFIRMATION_TTL = ENVIRONMENT.int("MCP_WRITE_CONFIRMATION_TTL", default=300)
MCP_PII_REDACTION_ENABLED = ENVIRONMENT.bool("MCP_PII_REDACTION_ENABLED", default=True)

# Manipulation of response to include ungrouped hosts id
ADD_UNGROUPED_HOSTS_ID = ENVIRONMENT.bool("ADD_UNGROUPED_HOSTS_ID", default=False)
REMOVE_NULL_VALUE = ENVIRONMENT.bool("REMOVE_NULL_VALUE", default=False)

# Service-to-service (S2S) authentication settings
SERVICE_PSKS = ENVIRONMENT.json("SERVICE_PSKS", default={})
SYSTEM_USERS = ENVIRONMENT.json("SYSTEM_USERS", default={})

# Principal caching settings
PRINCIPAL_CACHE_LIFETIME = ENVIRONMENT.int("PRINCIPAL_CACHE_LIFETIME", default=3600)

# Disaster recovery settings
DR_WORKSPACE_RECONCILE_ENABLED = ENVIRONMENT.bool("DR_WORKSPACE_RECONCILE_ENABLED", default=False)
DR_WORKSPACE_TOPIC = ENVIRONMENT.str("DR_WORKSPACE_TOPIC", default="outbox.event.workspace")
DR_KAFKA_CONSUMER_TIMEOUT_MS = ENVIRONMENT.int("DR_KAFKA_CONSUMER_TIMEOUT_MS", default=30000)
