# Generated by Django 2.2.4 on 2020-09-18 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.rbac_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0003_delete_user")]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account", models.CharField(max_length=15)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="CrossAccountRequest",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("target_account", models.CharField(max_length=15)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("startDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("endDate", models.DateTimeField()),
                ("modified", management.rbac_fields.AutoDateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="requested", max_length=10)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="employee", to="api.Employee"
                    ),
                ),
            ],
        ),
    ]
