# Generated by Django 2.2.4 on 2020-10-01 13:52

from django.db import migrations, models
import django.utils.timezone
import management.rbac_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0003_delete_user")]

    operations = [
        migrations.CreateModel(
            name="CrossAccountRequest",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("target_account", models.CharField(default=None, max_length=15)),
                ("userId", models.CharField(default=None, max_length=15)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("startDate", models.DateTimeField(default=django.utils.timezone.now)),
                ("endDate", models.DateTimeField(default=None)),
                ("modified", management.rbac_fields.AutoDateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="pending", max_length=10)),
            ],
        )
    ]
