# Generated by Django 2.2.4 on 2020-10-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0004_crossaccountrequest")]

    operations = [
        migrations.RenameField(model_name="crossaccountrequest", old_name="endDate", new_name="end_date"),
        migrations.RenameField(model_name="crossaccountrequest", old_name="startDate", new_name="start_date"),
        migrations.RenameField(model_name="crossaccountrequest", old_name="userId", new_name="user_id"),
    ]
