# Generated by Django 2.2.4 on 2020-12-07 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20201029_1731")]

    operations = [
        migrations.AlterField(
            model_name="crossaccountrequest", name="request_id", field=models.CharField(max_length=36, default=None)
        ),
        migrations.AddField(
            model_name="crossaccountrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
