# Generated by Django 2.2.4 on 2020-12-08 00:45

from django.db import migrations


def create_public_tenant(apps, schema_editor):
    Tenant = apps.get_model("api", "Tenant")
    Tenant.objects.get_or_create(schema_name="public")


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20201029_1731")]

    operations = [migrations.RunPython(create_public_tenant)]
