# Generated by Django 2.2.4 on 2020-12-03 17:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.rbac_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20201029_1731")]

    operations = [
        migrations.CreateModel(
            name="Access",
            fields=[("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"))],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("application", models.TextField()),
                ("resource_type", models.TextField()),
                ("verb", models.TextField()),
                ("permission", models.TextField(unique=True)),
                ("description", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("display_name", models.CharField(default="", max_length=150, unique=True)),
                ("description", models.TextField(null=True)),
                ("system", models.BooleanField(default=False)),
                ("platform_default", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", management.rbac_fields.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["name", "modified"]},
        ),
        migrations.CreateModel(
            name="ResourceDefinition",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attributeFilter", django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                (
                    "access",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resourceDefinitions",
                        to="api.Access",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="access",
            name="permission",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="accesses", to="api.Permission"
            ),
        ),
        migrations.AddField(
            model_name="access",
            name="role",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="access", to="api.Role"
            ),
        ),
    ]
