# Generated by Django 2.2.4 on 2020-12-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0030_auto_20201130_1845"), ("api", "0006_auto_20201208_0045")]

    operations = [
        migrations.AddField(
            model_name="crossaccountrequest",
            name="roles",
            field=models.ManyToManyField(related_name="cross_account_requests", to="management.Role"),
        )
    ]
