# Generated by Django 2.2.4 on 2021-07-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_auto_20201215_2221")]

    operations = [migrations.AddField(model_name="tenant", name="ready", field=models.BooleanField(default=False))]
