# Generated by Django 2.2.4 on 2020-12-16 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("api", "0007_auto_20201215_2221")]

    operations = [
        migrations.CreateModel(
            name="CrossAccountRequestHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_account", models.CharField(default=None, max_length=15)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("status", models.CharField(max_length=10)),
                (
                    "cross_account_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="api.CrossAccountRequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestHistoriesRoles",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cross_account_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.CrossAccountRequestHistory"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_account_request_histories",
                        to="management.Role",
                        to_field="uuid",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crossaccountrequesthistory",
            name="roles",
            field=models.ManyToManyField(through="api.RequestHistoriesRoles", to="management.Role"),
        ),
    ]
