# Generated by Django 2.2.24 on 2022-03-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20210722_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant", name="schema_name", field=models.CharField(db_index=True, max_length=63, unique=True),
        ),
    ]
