# Generated by Django 2.2.24 on 2022-03-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0011_rename_schema_name_to_tenant_name")]

    operations = [
        migrations.AddField(
            model_name="crossaccountrequest",
            name="target_org",
            field=models.CharField(default=None, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="account_id",
            field=models.CharField(default=None, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="org_id",
            field=models.CharField(default=None, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="crossaccountrequest",
            name="target_account",
            field=models.CharField(default=None, max_length=36),
        ),
    ]
