# Generated by Django 2.2.28 on 2022-06-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20220331_1924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crossaccountrequest",
            name="target_org",
            field=models.CharField(default=None, max_length=36),
        ),
    ]
