# Generated by Django 2.2.28 on 2022-07-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_auto_20220712_1249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crossaccountrequest",
            name="target_account",
            field=models.CharField(default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="crossaccountrequest",
            name="target_org",
            field=models.CharField(default=None, max_length=36),
        ),
    ]
