# Generated by Django 4.2.16 on 2024-11-25 19:48

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("api", "0014_auto_20220726_1743"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="tenant",
            index=models.Index(fields=["ready"], name="api_tenant_ready_c03ae0_idx"),
        ),
    ]
