# Generated by Django 4.2.23 on 2025-07-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_tenant_api_tenant_ready_c03ae0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="relations_consistency_token",
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
