# Generated by Django 4.2.23 on 2025-07-24 19:14

from django.db import migrations, models
import django.utils.timezone
import management.rbac_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0069_rolebinding_rolev2_rolebindingprincipal_and_more"),
        ("api", "0015_tenant_api_tenant_ready_c03ae0_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossAccountRequestV2",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "target_account",
                    models.CharField(default=None, max_length=36, null=True),
                ),
                ("target_org", models.CharField(default=None, max_length=36)),
                ("target_resource_type_namespace", models.CharField(max_length=256)),
                ("target_resource_type_name", models.CharField(max_length=256)),
                ("target_resource_id", models.CharField(max_length=256)),
                ("user_id", models.CharField(default=None, max_length=15)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(default=None)),
                (
                    "modified",
                    management.rbac_fields.AutoDateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.CharField(default="pending", max_length=10)),
                ("roles", models.ManyToManyField(to="management.rolev2")),
            ],
        ),
    ]
