# Generated by Django 6.0.7 on 2026-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_tenant_relations_consistency_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crossaccountrequest",
            name="status",
            field=models.CharField(db_index=True, default="pending", max_length=10),
        ),
    ]
