# Generated by Django 4.2.23 on 2025-07-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_crossaccountrequestv2"),
        ("management", "0069_rolebinding_rolev2_rolebindingprincipal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crossaccountrequestv2",
            name="roles",
            field=models.ManyToManyField(to="management.rolev2"),
        ),
    ]
