# Generated by Django 5.2 on 2026-08-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_crossaccountrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="org_config",
            field=models.JSONField(default=dict),
        ),
    ]
