DB_USER=$1

psql ${DATABASE_NAME} -p ${DATABASE_PORT} -h ${DATABASE_HOST} -U postgres -c "DROP DATABASE IF EXISTS test_${DATABASE_NAME};" || true

psql ${DATABASE_NAME} -p ${DATABASE_PORT} -h ${DATABASE_HOST} -U postgres -c "DROP USER ${DATABASE_USER};" || true

psql ${DATABASE_NAME} -p ${DATABASE_PORT} -h ${DATABASE_HOST} -U postgres -c "CREATE USER ${DATABASE_USER} WITH SUPERUSER LOGIN PASSWORD '${DATABASE_PASSWORD}';"
