kind: Template
apiVersion: v1
metadata:
  name: rbac-redis-template
  annotations:
    openshift.io/display-name: "RBAC"
    description:  "Redis for Role Based Access Control powered by Django+PostgreSQL+Celery"
    tags: "python,flask"
    iconClass: "icon-python"
    openshift.io/long-description: "This template defines resources needed to run the RBAC application, including a build configuration, application deployment configuration, and database deployment configuration."
    openshift.io/provider-display-name: "Red Hat, Inc."
    openshift.io/documentation-url: "https://insight-rbac.readthedocs.io/en/latest/"
labels:
  app: ${NAME}
  template: ${NAME}-redis-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: redis
    namespace: ${NAMESPACE}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: redis
        resourceVersion: latest
      name: "5.0.4"
      referencePolicy:
        type: Source
- apiVersion: v1
  data:
    redis.conf: |
      dir /var/lib/redis/data
    redis-service-host: ${NAME}-redis.${NAMESPACE}.svc
    redis-service-port: "6379"
  kind: ConfigMap
  metadata:
    name: redis-config
    namespace: ${NAMESPACE}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the redis service
      template.alpha.openshift.io/wait-for-ready: "true"
    labels:
      app: rbac
      template: rbac-template
    name: ${NAME}-redis
  spec:
    replicas: 1
    selector:
      name: ${NAME}-redis
    resources:
      limits:
        memory: ${MEMORY_REQUEST}
      limits:
        memory: ${MEMORY_LIMIT}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: rbac
          name: ${NAME}-redis
          template: rbac-template
        name: ${NAME}-redis
      spec:
        containers:
        - env:
          image: redis:5.0.4
          command:
            - "redis-server"
          args:
            - "/etc/redis/redis.conf"
          imagePullPolicy: IfNotPresent
          name: ${NAME}-redis
          ports:
          - containerPort: "6379"
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/redis/data
            name: ${NAME}-redis-data
          - mountPath: /etc/redis/
            name: ${NAME}-redis-config
        volumes:
          - name: ${NAME}-redis-data
            persistentVolumeClaim:
              claimName: ${NAME}-redis
          - name: ${NAME}-redis-config
            configMap:
              name: redis-config
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}-redis
        from:
          kind: ImageStreamTag
          name: redis:5.0.4
          namespace: ${NAMESPACE}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the redis service
    labels:
      app: rbac
      template: rbac-template
    name: ${NAME}-redis
  spec:
    ports:
    - name: ${NAME}-redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: ${NAME}-redis
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: koku
      template: koku-template
    name: ${NAME}-redis
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
parameters:
- description: The name assigned to all frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: rbac
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: myproject
- description: Initial amount of memory the container will request.
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 1Gi
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Volume space available for data, e.g. 512Mi, 2Gi
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi