# Generated by Django 2.1.5 on 2019-02-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
