# Generated by Django 2.1.5 on 2019-04-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("management", "0004_auto_20190318_2359")]

    operations = [migrations.RemoveField(model_name="principal", name="email")]
