# Generated by Django 2.2.4 on 2019-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20190407_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='platform_default',
            field=models.BooleanField(default=False),
        ),
    ]
