# Generated by Django 2.2.4 on 2019-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0006_auto_20190407_1332")]

    operations = [migrations.AddField(model_name="policy", name="system", field=models.BooleanField(default=False))]
