# Generated by Django 2.2.4 on 2019-11-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_policy_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='platform_default',
            field=models.BooleanField(default=False),
        ),
    ]
