# Generated by Django 2.2.4 on 2019-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0007_policy_system")]

    operations = [
        migrations.AddField(model_name="group", name="platform_default", field=models.BooleanField(default=False))
    ]
