# Generated by Django 2.2.4 on 2019-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0009_role_platform_default")]

    operations = [migrations.AddField(model_name="group", name="system", field=models.BooleanField(default=False))]
