# Generated by Django 2.2.4 on 2020-01-28 20:30

from django.db import migrations


def remove_unnecessary_platform_default_role(apps, schema_editor):
    role_names_to_remove = [
        "Ansible Automation Access",
        "Ansible Hub Access",
        "Catalog Access",
        "Remediations Access",
        "Sources Access",
        "Subscriptions Access",
    ]

    Role = apps.get_model("management", "Role")
    Role.objects.filter(system=True, name__in=role_names_to_remove).delete()


class Migration(migrations.Migration):

    dependencies = [("management", "0012_remove_RonR_resources")]

    operations = [migrations.RunPython(remove_unnecessary_platform_default_role)]
