# Generated by Django 2.2.4 on 2020-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0013_auto_20200128_2030")]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app", models.TextField()),
                ("resource", models.TextField()),
                ("operation", models.TextField()),
                ("permission", models.TextField(unique=True)),
            ],
        )
    ]
