# Generated by Django 2.2.4 on 2020-06-08 14:57

from django.db import migrations, models
import django.db.models.deletion


def replicate_permission(apps, schema_editor):
    # get all permissions/access objects
    Access = apps.get_model("management", "Access")
    Permission = apps.get_model("management", "Permission")

    # iterate through all Access
    for access in Access.objects.all():
        # get the permission context from the permission
        permission, _ = Permission.objects.get_or_create(permission=access.perm)
        permission.access.add(access)


class Migration(migrations.Migration):

    dependencies = [("management", "0014_add_model_permission")]

    operations = [
        migrations.RenameField(model_name="access", old_name="permission", new_name="perm"),
        migrations.AddField(
            model_name="access",
            name="permission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access",
                to="management.Permission",
            ),
        ),
        migrations.RunPython(replicate_permission),
    ]
