# Generated by Django 2.2.4 on 2020-07-16 15:08

from django.db import migrations


def populate_permissions(apps, schema_editor):
    Permission = apps.get_model("management", "Permission")
    perms = Permission.objects.all()
    for p in perms:
        if not p.permission:
            continue

        split_permission = p.permission.split(":")

        if len(split_permission) != 3:
            continue

        p.app, p.resource, p.operation = split_permission
        p.save()


class Migration(migrations.Migration):

    dependencies = [("management", "0016_make_bridge_for_migration")]

    operations = [migrations.RunPython(populate_permissions)]
