# Generated by Django 2.2.4 on 2020-07-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0018_add_display_name_field_to_role"),
    ]

    operations = [
        migrations.RemoveField(model_name="role", name="display_name",),
        migrations.AddField(
            model_name="role", name="display_name", field=models.CharField(null=True, max_length=150),
        ),
    ]
