# Generated by Django 2.2.4 on 2020-10-08 14:19

from django.db import migrations


def remove_insights_permissions(apps, schema_editor):
    Permission = apps.get_model("management", "Permission")
    Permission.objects.filter(application="insights").delete()


class Migration(migrations.Migration):

    dependencies = [("management", "0020_add_unique_to_display_name")]

    operations = [migrations.RunPython(remove_insights_permissions)]
