# Generated by Django 2.2.4 on 2020-10-09 18:10

from django.db import migrations


def update_default_group_name(apps, schema_editor):
    Group = apps.get_model("management", "Group")
    for group in Group.objects.all(platform_default=True):
        if group.system and group.platform_default:
            group.name = "Default access"
        elif group.platform_default:
            group.name = "Custom default access"
        group.save()


class Migration(migrations.Migration):

    dependencies = [("management", "0020_add_unique_to_display_name")]

    operations = [migrations.RunPython(update_default_group_name)]
