# Generated by Django 2.2.4 on 2020-09-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("management", "0021_auto_20201008_1419")]

    operations = [migrations.RemoveField(model_name="access", name="permission")]
