# Generated by Django 2.2.4 on 2020-09-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("management", "0023_remove_access_permission")]

    operations = [
        migrations.AddField(
            model_name="access",
            name="permission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accesses",
                to="management.Permission",
            ),
        )
    ]
