# Generated by Django 2.2.4 on 2020-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0025_auto_20201028_1619")]

    operations = [migrations.AddField(model_name="permission", name="description", field=models.TextField(default=""))]
