# Generated by Django 2.2.4 on 2020-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("management", "0026_permission_description")]

    operations = [
        migrations.AlterField(
            model_name="permission", name="description", field=models.TextField(default="", null=True)
        )
    ]
