# Generated by JayZ 2.2.4 on 2020-09-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("management", "0027_auto_20201103_1956")]

    operations = [migrations.RemoveField(model_name="access", name="permission")]
