# Generated by JayZ 2.2.4 on 2020-09-28 15:57

from django.db import migrations, models
import django.db.models.deletion

from django.db import migrations, models


def sync_permission(apps, schema_editor):
    # get access model
    Access = apps.get_model("management", "Access")
    Permission = apps.get_model("management", "Permission")

    # iterate through all Access
    for access in Access.objects.all():
        # get the permission context from the perm
        permission, created = Permission.objects.get_or_create(permission=access.perm)
        access.permission = permission
        access.save()


class Migration(migrations.Migration):

    dependencies = [("management", "0027_auto_20201103_1956")]

    operations = [
        migrations.RemoveField(model_name="access", name="permission"),
        migrations.RunPython(sync_permission),
    ]
