# Generated by Django 2.2.4 on 2020-11-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("management", "0028_sync_perm_and_permission")]

    operations = [migrations.RemoveField(model_name="access", name="perm")]
