# Generated by Django 2.2.4 on 2020-12-04 18:32

from django.db import migrations, models


def remove_description_none(apps, schema_editor):
    Permission = apps.get_model("management", "Permission")
    Permission.objects.filter(description=None).update(description="")


class Migration(migrations.Migration):

    dependencies = [("management", "0028_sync_perm_and_permission")]

    operations = [
        migrations.AlterField(model_name="permission", name="description", field=models.TextField(default="")),
        migrations.RunPython(remove_description_none),
    ]
