# Generated by Django 2.2.4 on 2020-11-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("management", "0029_auto_20201204_1832")]

    operations = [migrations.RemoveField(model_name="access", name="perm")]
