# Generated by Django 2.2.4 on 2021-02-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("management", "0030_auto_20201130_1845")]

    operations = [
        migrations.AddField(model_name="principal", name="cross_account", field=models.BooleanField(default=False)),
        migrations.RunSQL("ALTER TABLE ONLY management_principal ALTER COLUMN cross_account SET DEFAULT false;"),
    ]
