# Generated by Django 2.2.4 on 2021-03-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0007_auto_20201215_2221"), ("management", "0031_auto_20210203_2212")]

    operations = [
        migrations.AddField(
            model_name="access",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AddField(
            model_name="principal",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AddField(
            model_name="resourcedefinition",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
    ]
