# Generated by Django 2.2.4 on 2021-04-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_add_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='principal',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='role',
            name='display_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
