# Generated by Django 2.2.24 on 2021-10-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("management", "0034_remove_field_uniqueness")]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="permissions",
            field=models.ManyToManyField(related_name="required_permissions", to="management.Permission"),
        )
    ]
