# Generated by Django 2.2.24 on 2022-05-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0037_auto_20220114_1822"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtTenant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtRoleRelation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ext_id", models.CharField(max_length=20)),
                (
                    "ext_tenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ext_role_relation",
                        to="management.ExtTenant",
                    ),
                ),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="management.Role", related_name="ext_relation"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="extrolerelation",
            constraint=models.UniqueConstraint(
                fields=("ext_tenant", "ext_id"), name="unique external id per external tenant"
            ),
        ),
    ]
