# Generated by Django 2.2.28 on 2022-07-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0038_auto_20220512_1800"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="permission",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accesses",
                to="management.Permission",
            ),
        ),
        migrations.AlterField(
            model_name="access",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AlterField(
            model_name="principal",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AlterField(
            model_name="resourcedefinition",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Tenant"
            ),
        ),
    ]
