# Generated by Django 4.1.7 on 2023-08-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20220726_1743"),
        ("management", "0040_access_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requester", models.TextField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("group", "Group"),
                            ("role", "Role"),
                            ("user", "User"),
                            ("permission", "Permission"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Add", "Add"),
                            ("Delete", "Delete"),
                            ("Create", "Create"),
                            ("Edit", "Edit"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.tenant"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
