# Generated by Django 3.2.17 on 2023-02-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0040_access_permission"),
    ]
    operations = [
        migrations.AddField(model_name="principal", name="type", field=models.TextField(default="user", null=False)),
        migrations.AddField(model_name="principal", name="service_account_id", field=models.TextField(null=True)),
    ]
