# Generated by Django 4.1.7 on 2023-08-28 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_workspace_permission_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
