# Generated by Django 4.1.7 on 2023-08-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0041_auditlogmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlogmodel",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="auditlogmodel",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="auditlogmodel",
            name="action",
            field=models.CharField(
                choices=[
                    ("Add", "Add"),
                    ("Delete", "Delete"),
                    ("Create", "Create"),
                    ("Edit", "Edit"),
                    ("Remove", "Remove"),
                ],
                max_length=32,
            ),
        ),
    ]
