# Generated by Django 4.1.7 on 2023-08-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0042_remove_auditlogmodel_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditlogmodel",
            name="tenant",
        ),
    ]
