# Generated by Django 4.1.10 on 2023-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0042_service_accounts_update_usernames_format_RHCLOUD_29429"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="zed_token",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="principal",
            name="service_account_id",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
