# Generated by Django 4.2.7 on 2023-12-13 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0042_service_accounts_update_usernames_format_RHCLOUD_29429"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("requester", models.TextField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("group", "Group"),
                            ("role", "Role"),
                            ("user", "User"),
                            ("permission", "Permission"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("delete", "Delete"),
                            ("add", "Add"),
                            ("edit", "Edit"),
                            ("create", "Create"),
                            ("remove", "Remove"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
