# Generated by Django 4.1.7 on 2023-09-07 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0042_workspace_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("permission", "workspace")},
        ),
    ]
