# Generated by Django 4.1.7 on 2023-09-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0043_alter_workspace_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="permission",
            field=models.TextField(),
        ),
    ]
