# Generated by Django 4.2.10 on 2024-07-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0044_workspace"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workspace",
            name="The combination of 'name', 'tenant', and 'parent' must be unique.",
        ),
        migrations.AlterField(
            model_name="workspace",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="parent",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
