# Generated by Django 4.1.10 on 2023-11-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0041_service_account_support_ADR_036_RHCLOUD_27878"),
        ("management", "0045_alter_auditlogmodel_action_and_more"),
    ]

    operations = []
