# Generated by Django 4.1.10 on 2023-11-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0046_merge_20231110_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogmodel",
            name="action",
            field=models.CharField(
                choices=[
                    ("delete", "Delete"),
                    ("add", "Add"),
                    ("edit", "Edit"),
                    ("create", "Create"),
                    ("remove", "Remove"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auditlogmodel",
            name="resource",
            field=models.CharField(
                choices=[
                    ("group", "Group"),
                    ("role", "Role"),
                    ("user", "User"),
                    ("permission", "Permission"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="principal",
            name="service_account_id",
            field=models.TextField(),
        ),
    ]
