# Generated by Django 4.2.15 on 2024-08-12 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_remove_workspace_the_combination_of_name_tenant_and_parent_must_be_unique__and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=75)),
                ('aggregate_id', models.CharField(max_length=50)),
                ('payload', models.BinaryField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
