# Generated by Django 4.2.14 on 2024-08-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0047_rolemapping_rolev2_rolemapping_role_v2_rolebinding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="management.workspace",
                to_field="uuid",
            ),
        ),
    ]
