# Generated by Django 4.2.15 on 2024-08-21 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0047_rolemapping_rolev2_rolemapping_role_v2_rolebinding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("aggregatetype", models.CharField(max_length=255)),
                ("aggregateid", models.CharField(max_length=255)),
                ("event_type", models.CharField(db_column="type", max_length=255)),
                ("payload", models.JSONField()),
            ],
        ),
    ]
