# Generated by Django 4.2.15 on 2024-08-21 15:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0047_rolemapping_rolev2_rolemapping_role_v2_rolebinding"),
    ]

    operations = [
        migrations.AddField(
            model_name="bindingmapping",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="bindingmapping",
            name="v2_role",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="management.v2role"),
            preserve_default=False,
        ),
    ]
