# Generated by Django 4.2.15 on 2024-09-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0049_alter_workspace_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("group", "Group"),
                    ("role", "Role"),
                    ("user", "User"),
                    ("permission", "Permission"),
                    ("service_account", "Service_account"),
                ],
                max_length=32,
            ),
        ),
    ]
