# Generated by Django 4.2.10 on 2024-09-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0049_alter_workspace_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="principal",
            name="user_id",
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="principal",
            name="type",
            field=models.CharField(
                choices=[("user", "User"), ("service-account", "Service Account")],
                default="user",
                max_length=20,
            ),
        ),
    ]
