# Generated by Django 4.2.15 on 2024-08-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0050_principal_user_id_alter_principal_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolemapping",
            name="v1_role",
        ),
        migrations.RemoveField(
            model_name="rolemapping",
            name="v2_role",
        ),
        migrations.RemoveField(
            model_name="v2role",
            name="v1_roles",
        ),
        migrations.DeleteModel(
            name="BindingMapping",
        ),
        migrations.DeleteModel(
            name="RoleMapping",
        ),
        migrations.DeleteModel(
            name="V2Role",
        ),
    ]
