# Generated by Django 4.2.10 on 2024-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0050_principal_user_id_alter_principal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="principal",
            name="user_id",
            field=models.CharField(db_index=True, max_length=256, null=True),
        ),
    ]
