# Generated by Django 4.2.15 on 2024-09-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0050_principal_user_id_alter_principal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("default", "Default"),
                    ("root", "Root"),
                ],
                default="standard",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type__in", ["root", "default"])),
                fields=("tenant_id", "type"),
                name="unique_default_root_workspace_per_tenant",
            ),
        ),
    ]
