# Generated by Django 4.2.15 on 2024-10-09 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20220726_1743"),
        ("management", "0054_bindingmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_group_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "default_admin_group_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "default_user_role_binding_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "default_admin_role_binding_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tenant"
                    ),
                ),
            ],
        ),
    ]
