# Generated by Django 4.2.15 on 2024-10-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0055_tenantmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_uuid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="management.workspace",
                to_field="uuid",
            ),
        ),
    ]
