# Generated by Django 4.2.16 on 2024-11-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0058_rename_uuid_workspace_id_workspace_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="principal",
            name="service_account_id",
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="principal",
            name="type",
            field=models.CharField(
                choices=[("user", "User"), ("service-account", "Service Account")],
                db_index=True,
                default="user",
                max_length=20,
            ),
        ),
    ]
