# Generated by Django 4.2.16 on 2024-11-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0059_alter_principal_service_account_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="management.workspace",
            ),
        ),
    ]
