# Generated by Django 4.2.16 on 2024-11-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0060_alter_workspace_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="management.workspace",
            ),
        ),
    ]
