# Generated by Django 4.2.16 on 2025-02-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0061_alter_workspace_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
