# Generated by Django 4.2.16 on 2025-01-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0061_alter_workspace_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workspace",
            options={},
        ),
    ]
