# Generated by Django 4.2.16 on 2025-02-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0064_alter_workspace_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workspace",
            name="unique_default_root_workspace_per_tenant",
        ),
        migrations.AlterField(
            model_name="workspace",
            name="type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("default", "Default"),
                    ("root", "Root"),
                    ("ungrouped-hosts", "Ungrouped Hosts"),
                ],
                default="standard",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type__in", ["root", "default", "ungrouped-hosts"])),
                fields=("tenant_id", "type"),
                name="unique_default_root_workspace_per_tenant",
            ),
        ),
    ]
