# Generated by Django 4.2.16 on 2025-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0065_remove_workspace_unique_default_root_workspace_per_tenant_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("name", "parent"),
                name="unique_workspace_name_per_parent",
            ),
        ),
    ]
