# Generated by Django 4.2.20 on 2025-04-22 18:41

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0066_workspace_unique_workspace_name_per_parent"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workspace",
            name="unique_workspace_name_per_parent",
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("name"),
                models.F("parent"),
                condition=models.Q(("parent__isnull", False)),
                name="unique_workspace_name_per_parent",
            ),
        ),
    ]
