# Generated by Django 4.2.20 on 2025-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0067_remove_workspace_unique_workspace_name_per_parent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("default", "Default"),
                    ("root", "Root"),
                    ("ungrouped-hosts", "Ungrouped Hosts"),
                ],
                db_index=True,
                default="standard",
            ),
        ),
    ]
