# Generated by Django 4.2.23 on 2025-06-27 21:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0068_alter_workspace_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
