# Generated by Django 4.2.23 on 2025-06-27 21:29

from django.db import migrations, models
from django.shortcuts import get_object_or_404
from management.role.model import Role
from management.group.model import Group
from management.permission.model import Permission
import uuid


def populate_new_uuid_field(apps, schema_editor):
    AuditLog = apps.get_model("management", "auditlog")
    for obj in AuditLog.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])


def populate_resource_uuid_field(apps, schema_editor):
    AuditLog = apps.get_model("management", "auditlog")
    for obj in AuditLog.objects.all():
        if obj.resource_type == "Role":
            find_role = get_object_or_404(Role, id=obj.resource_id)
            obj.resource_uuid = find_role.uuid
        if obj.resource_type == "Group":
            find_group = get_object_or_404(Group, id=obj.resource_id)
            obj.resource_uuid = find_group.uuid
        if obj.resource_type == "Permission":
            find_permission = get_object_or_404(Permission, id=obj.resource_id)
            obj.resource_uuid = find_permission.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0068_alter_workspace_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(populate_new_uuid_field, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="auditlog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="resource_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.RunPython(populate_resource_uuid_field, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="secondary_resource_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
