# Generated by Django 4.2.23 on 2025-07-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0068_alter_workspace_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="resource_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="secondary_resource_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
