# Generated by Django 4.2.23 on 2025-09-12 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0069_auditlog_resource_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmapping",
            name="root_scope_default_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="tenantmapping",
            name="root_scope_default_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="tenantmapping",
            name="tenant_scope_default_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="tenantmapping",
            name="tenant_scope_default_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
