# Generated by Django 4.2.23 on 2025-06-27 21:31
import uuid
from django.db import migrations


def populate_new_uuid_field(apps, schema_editor):
    AuditLog = apps.get_model("management", "auditlog")
    for obj in AuditLog.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0069_auditlog_uuid"),
    ]
    operations = [
        migrations.RunPython(populate_new_uuid_field, reverse_code=migrations.RunPython.noop),
    ]
