# Generated by Django 4.2.23 on 2025-07-25 17:58

from django.db import migrations


def create_public_v2_roles(apps, schema_editor):
    Tenant = apps.get_model("api", "Tenant")
    RoleV2 = apps.get_model("management", "RoleV2")

    all_users_type = "platform-all-users"
    all_admins_type = "platform-all-admins"

    if RoleV2.objects.filter(type=all_users_type).exists():
        raise ValueError('An "all users" role already exists.')

    if RoleV2.objects.filter(type=all_admins_type).exists():
        raise ValueError('An "all admins" role already exists.')

    public_tenant = Tenant.objects.get(tenant_name="public")

    RoleV2.objects.create(
        tenant=public_tenant,
        name="All users",
        display_name="All users",
        type=all_users_type,
    )

    RoleV2.objects.create(
        tenant=public_tenant,
        name="All admins",
        display_name="All admins",
        type=all_admins_type,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0069_rolebinding_rolev2_rolebindingprincipal_and_more"),
    ]

    operations = [migrations.RunPython(create_public_v2_roles)]
