# Generated by Django 4.2.23 on 2025-07-29 19:45

from django.db import migrations


def create_public_v2_roles(apps, schema_editor):
    Tenant = apps.get_model("api", "Tenant")
    RoleV2 = apps.get_model("management", "RoleV2")

    default_users_name = "platform-default-users"
    default_admins_name = "platform-default-admins"

    public_tenant = Tenant.objects.get(tenant_name="public")

    if RoleV2.objects.filter(tenant=public_tenant, name=default_users_name).exists():
        raise ValueError("The platform default users role already exists.")

    if RoleV2.objects.filter(tenant=public_tenant, name=default_admins_name).exists():
        raise ValueError("The platform default admins role already exists.")

    RoleV2.objects.create(
        tenant=public_tenant,
        name=default_users_name,
        display_name="Default user access",
        type="system",
    )

    RoleV2.objects.create(
        tenant=public_tenant,
        name=default_admins_name,
        display_name="Default admin access",
        type="system",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0069_rolebinding_rolev2_rolebindingprincipal_and_more"),
    ]

    operations = [migrations.RunPython(create_public_v2_roles)]
