# Generated by Django for additional role binding UUIDs

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0069_auditlog_resource_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmapping",
            name="root_scope_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="tenantmapping",
            name="root_scope_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="tenantmapping",
            name="tenant_scope_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="tenantmapping",
            name="tenant_scope_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
