# Generated by Django 4.2.23 on 2025-07-18 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0069_rolev2_rolebinding_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolebinding",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="rolebinding",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
