# Generated by Django 4.2.24 on 2025-09-23 20:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.rbac_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("api", "0016_tenant_relations_consistency_token"),
        (
            "management",
            "0070_tenantmapping_root_scope_default_admin_role_binding_uuid_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleV2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("display_name", models.CharField(default="", max_length=150)),
                ("description", models.TextField(null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified",
                    management.rbac_fields.AutoDateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "children",
                    models.ManyToManyField(related_name="parents", to="management.rolev2"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(related_name="v2_roles", to="management.permission"),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.tenant"),
                ),
                (
                    "v1_source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="v2_roles",
                        to="management.role",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "modified"],
            },
        ),
        migrations.CreateModel(
            name="CustomRole",
            fields=[
                (
                    "rolev2_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="management.rolev2",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("management.rolev2",),
        ),
        migrations.CreateModel(
            name="PlatformRole",
            fields=[
                (
                    "rolev2_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="management.rolev2",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("management.rolev2",),
        ),
        migrations.CreateModel(
            name="SeededRole",
            fields=[
                (
                    "rolev2_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="management.rolev2",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("management.rolev2",),
        ),
        migrations.AddConstraint(
            model_name="rolev2",
            constraint=models.UniqueConstraint(fields=("name", "tenant"), name="unique role v2 name per tenant"),
        ),
        migrations.AddConstraint(
            model_name="rolev2",
            constraint=models.UniqueConstraint(
                fields=("display_name", "tenant"),
                name="unique role v2 display name per tenant",
            ),
        ),
    ]
