# Generated by Django 4.2.23 on 2025-07-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0070_remove_rolebinding_uuid_alter_rolebinding_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolev2",
            name="v1_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="v2_roles",
                to="management.role",
            ),
        ),
    ]
