# Generated by Django 4.2.24 on 2025-09-30 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import management.rbac_fields
import management.role.v2_model
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_tenant_relations_consistency_token"),
        (
            "management",
            "0070_tenantmapping_root_scope_default_admin_role_binding_uuid_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleV2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("seeded", "Seeded"),
                            ("platform", "Platform"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "modified",
                    management.rbac_fields.AutoDateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "children",
                    models.ManyToManyField(related_name="parents", to="management.rolev2"),
                ),
                (
                    "permissions",
                    models.ManyToManyField(related_name="v2_roles", to="management.permission"),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.tenant"),
                ),
                (
                    "v1_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="v2_roles",
                        to="management.role",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "modified"],
            },
        ),
        migrations.CreateModel(
            name="CustomRoleV2",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                management.role.v2_model.TypeValidatedRoleV2Mixin,
                "management.rolev2",
            ),
        ),
        migrations.CreateModel(
            name="PlatformRoleV2",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                management.role.v2_model.TypeValidatedRoleV2Mixin,
                "management.rolev2",
            ),
        ),
        migrations.CreateModel(
            name="SeededRoleV2",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                management.role.v2_model.TypeValidatedRoleV2Mixin,
                "management.rolev2",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolev2",
            constraint=models.UniqueConstraint(fields=("name", "tenant"), name="unique role v2 name per tenant"),
        ),
    ]
