# Generated by Django 4.2.23 on 2025-06-27 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0070_populate_new_uuid_field_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
