# Generated by Django 4.2.25 on 2025-10-06 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid_utils.compat


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_tenant_relations_consistency_token"),
        ("management", "0071_rolev2_customrolev2_platformrolev2_seededrolev2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleBinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, unique=True),
                ),
                ("resource_type", models.CharField(max_length=256)),
                ("resource_id", models.CharField(max_length=256)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bindings",
                        to="management.rolev2",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.tenant"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleBindingGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_entries",
                        to="management.rolebinding",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_binding_entries",
                        to="management.group",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="rolebindinggroup",
            constraint=models.UniqueConstraint(fields=("group", "binding"), name="unique group binding pair"),
        ),
        migrations.AddConstraint(
            model_name="rolebinding",
            constraint=models.UniqueConstraint(
                fields=("role", "resource_type", "resource_id", "tenant"),
                name="unique role binding per role resource pair per tenant",
            ),
        ),
    ]
