# Generated by Django 4.2.23 on 2025-07-03 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0071_alter_auditlog_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="resource_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
