# Generated by Django 5.2.7 on 2025-11-12 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0072_rolebinding_rolebindinggroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantmapping",
            name="default_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="default_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="root_scope_default_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="root_scope_default_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="tenant_scope_default_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="tenant_scope_default_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
