# Generated by Django 5.2.7 on 2025-12-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0072_rolebinding_rolebindinggroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolev2",
            name="v1_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="v2_roles",
                to="management.role",
            ),
        ),
    ]
