# Generated by Django 4.2.23 on 2025-07-03 19:02

from django.db import migrations
from django.shortcuts import get_object_or_404
from management.role.model import Role
from management.group.model import Group
from management.permission.model import Permission
import uuid


def populate_resource_uuid_field(apps, schema_editor):
    AuditLog = apps.get_model("management", "auditlog")
    for obj in AuditLog.objects.all():
        if obj.resource_type == "Role":
            find_role = get_object_or_404(Role, id=obj.resource_id)
            print(find_role.uuid)
            obj.resource_uuid = find_role.uuid
        if obj.resource_type == "Group":
            find_group = get_object_or_404(Group, id=obj.resource_id)
            obj.resource_uuid = find_group.uuid
        if obj.resource_type == "Permission":
            find_permission = get_object_or_404(Permission, id=obj.resource_id)
            obj.resource_uuid = find_permission.uuid


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0072_auditlog_resource_uuid"),
    ]
    operations = [
        migrations.RunPython(populate_resource_uuid_field, reverse_code=migrations.RunPython.noop),
    ]
