# Generated by Django 4.2.23 on 2025-07-03 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0073_populate_resource_uuid_field_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="resource_uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
