# Generated by Django 5.2.7 on 2025-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0073_alter_rolev2_v1_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolev2",
            name="name",
            field=models.CharField(max_length=175),
        ),
    ]
