# Generated by Django 4.2.23 on 2025-07-09 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0074_alter_auditlog_resource_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="resource_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
