# Generated by Django 5.2.10 on 2026-01-14 18:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0074_alter_rolev2_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantmapping",
            name="default_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="default_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="root_scope_default_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="root_scope_default_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="tenant_scope_default_admin_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantmapping",
            name="tenant_scope_default_role_binding_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
