# Generated by Django 4.2.23 on 2025-07-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0075_alter_auditlog_resource_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="secondary_resource_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
