# Generated by Django 5.2.10 on 2026-01-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0076_add_unique_constraint_principal_user_id"),
        ("management", "0076_rolebindingprincipal"),
    ]

    operations = []
