# Generated by Django 5.2.10 on 2026-01-26 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0076_add_unique_constraint_principal_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleBindingPrincipal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=128)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principal_entries",
                        to="management.rolebinding",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_binding_entries",
                        to="management.principal",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("principal", "binding", "source"),
                        name="unique principal binding source triple",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", ""), _negated=True),
                        name="role binding principal has source",
                    ),
                ],
            },
        ),
    ]
