# Generated by Django 5.2.11 on 2026-03-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_tenant_relations_consistency_token"),
        ("management", "0077_rolebindingprincipal"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["tenant", "created"], name="management__tenant__f20f75_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "resource_type"],
                name="management__tenant__9132ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["tenant", "action"], name="management__tenant__130cc6_idx"),
        ),
    ]
