# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0078_add_auditlog_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmapping",
            name="v2_write_activated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
