# Generated by Django 5.2.12 on 2026-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0079_tenantmapping_v2_write_activated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("group", "Group"),
                    ("role", "Role"),
                    ("role_v2", "V2 Role"),
                    ("user", "User"),
                    ("permission", "Permission"),
                ],
                max_length=32,
            ),
        ),
    ]
