# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0080_alter_auditlog_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolebindinggroup",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="rolebindingprincipal",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
