# Generated by Django 5.2.12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0081_rolebinding_created_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolebindinggroup",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="rolebindingprincipal",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
