# Generated by Django 5.2.12 on 2026-04-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0082_alter_rolebindinggroup_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolebindinggroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_binding_entries",
                to="management.group",
            ),
        ),
        migrations.AlterField(
            model_name="rolebindingprincipal",
            name="principal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="role_binding_entries",
                to="management.principal",
            ),
        ),
    ]
