# Generated by Django 5.2.12 on 2026-04-08

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0083_alter_rolebindinggroup_group_and_more"),
    ]

    operations = [
        # Enable the pg_trgm extension (idempotent — safe if already enabled).
        TrigramExtension(),
        # GIN trigram index on RoleV2.name for iexact / iregex queries.
        migrations.AddIndex(
            model_name="rolev2",
            index=GinIndex(
                fields=["name"],
                name="rolev2_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        # GIN trigram index on Workspace.name for icontains queries.
        migrations.AddIndex(
            model_name="workspace",
            index=GinIndex(
                fields=["name"],
                name="workspace_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
