# Generated by Django 5.2.12 on 2026-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0084_add_gin_trgm_indexes_for_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("group", "Group"),
                    ("role", "Role"),
                    ("role_v2", "V2 Role"),
                    ("user", "User"),
                    ("permission", "Permission"),
                    ("workspace", "Workspace"),
                ],
                max_length=32,
            ),
        ),
    ]
