# Generated by Django 5.2.13 on 2026-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0085_alter_auditlog_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("group", "Group"),
                    ("role", "Role"),
                    ("role_v2", "V2 Role"),
                    ("user", "User"),
                    ("permission", "Permission"),
                    ("workspace", "Workspace"),
                    ("role_binding", "Role Binding"),
                ],
                max_length=32,
            ),
        ),
    ]
