# Generated by Django 5.2.13 on 2026-04-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0087_alter_extrolerelation_ext_id_alter_exttenant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolev2",
            name="last_seed_scope",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
