# Generated by Django 6.0.6 on 2026-06-17 14:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0090_backfill_bindingmapping_v2_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleScopeState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=0)),
                (
                    "computed_scopes",
                    django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField()),
                ),
                ("migrated", models.BooleanField(default=False)),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_state",
                        to="management.role",
                    ),
                ),
            ],
        ),
    ]
