# Generated by Django 6.0.6 on 2026-06-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0091_add_read_action_to_audit_log"),
        ("management", "0091_rolescopestate"),
    ]

    operations = []
