# Generated by Django 6.0.7 on 2026-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0092_merge_audit_log_read_and_rolescopestate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="principal_username",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="permission",
            name="application",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="permission",
            name="permission",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="resource_type",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="permission",
            name="verb",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="principal",
            name="service_account_id",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
