# Generated by Django 6.0.6 on 2026-08-06 19:22

from django.db import migrations, models
from django.db.models import F


def set_opted_in_for_v2_tenants(apps, schema_editor):
    apps.get_model("management", "TenantMapping").objects.filter(v2_write_activated_at__isnull=False).update(
        v2_opted_in_at=F("v2_write_activated_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_crossaccountrequest_status"),
        ("management", "0093_charfield_and_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmapping",
            name="v2_opted_in_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        # We do not need to be able to undo this step, since we'll just be dropping the column anyway if undoing this
        # migration.
        migrations.RunPython(code=set_opted_in_for_v2_tenants, reverse_code=lambda *args: None),
        migrations.AddConstraint(
            model_name="tenantmapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("v2_write_activated_at__isnull", True),
                    ("v2_opted_in_at__isnull", False),
                    _connector="OR",
                ),
                name="V2 write activated only if opted in",
            ),
        ),
    ]
