name: Check Quay Image

on:
  push:
    branches:
      - master

jobs:
  check-image:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Quay image
        uses: petracihalova/check-quay-image@v1
        with:
          quay_repo: redhat-services-prod/hcc-accessmanagement-tenant/insights-rbac
          commit_sha: ${{ github.sha }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          delay_minutes: 5
