name: Check Quay Image

on:
  check_run:
    types:
      - completed

jobs:
  check-image:
    runs-on: ubuntu-latest
    if: >-
      github.event.check_run.name == 'Red Hat Konflux / insights-rbac-on-push' &&
      github.event.check_run.conclusion == 'success' &&
      github.event.check_run.app.slug == 'red-hat-konflux'
    steps:
      - name: Wait for Quay image
        uses: petracihalova/check-quay-image@v1
        with:
          quay_repo: redhat-services-prod/hcc-accessmanagement-tenant/insights-rbac
          commit_sha: ${{ github.event.check_run.head_sha }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          delay_minutes: 5
