apiVersion: v1
kind: Template
metadata:
  name: kafka-connect
parameters:
  - name: KAFKA_CONNECT_IMAGE
    description: Image for kafka connect instance
    value: quay.io/cloudservices/kafka-connect
  - name: IMAGE_TAG
    description: Tag to use for this deploy of kafka connect
    value: latest
  - name: KAFKA_CONNECT_VERSION
    description: Version of the kafka-connect service
    value: 3.6.0
  - name: KAFKA_CONNECT_REPLICAS
    description: Number of connect instances to run
    value: "1"
  - name: KAFKA_CONNECT_CPU_LIMIT
    value: "1"
  - name: KAFKA_CONNECT_MEM_LIMIT
    value: 2Gi
  - name: KAFKA_CONNECT_CPU_REQUEST
    value: 500m
  - name: KAFKA_CONNECT_MEM_REQUEST
    value: 1Gi
  - name: ENV_NAME
    required: true
objects:
  - apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaConnect
    metadata:
      name: platform-kafka-connect
      labels:
        app: platform-mq
      annotations:
        strimzi.io/use-connector-resources: "true"
    spec:
      image: ${KAFKA_CONNECT_IMAGE}:${IMAGE_TAG}
      template:
        pod:
          imagePullSecrets:
            - name: quay-cloudservices-pull
            - name: rh-registry-pull
            - name: quay.io
      version: ${KAFKA_CONNECT_VERSION}
      replicas: ${{KAFKA_CONNECT_REPLICAS}}
      resources:
        limits:
          cpu: ${KAFKA_CONNECT_CPU_LIMIT}
          memory: ${KAFKA_CONNECT_MEM_LIMIT}
        requests:
          cpu: ${KAFKA_CONNECT_CPU_REQUEST}
          memory: ${KAFKA_CONNECT_MEM_REQUEST}
      bootstrapServers: ${ENV_NAME}-kafka-bootstrap:9092
      config:
        config.providers: secrets
        config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider

        group.id: rbac-connect-cluster

        offset.storage.topic: rbac-platform-connect-cluster-offsets
        config.storage.topic: rbac-platform-connect-cluster-configs
        status.storage.topic: rbac-platform-connect-cluster-status

        offset.storage.replication.factor: "1"
        config.storage.replication.factor: "1"
        status.storage.replication.factor: "1"

        connector.client.config.override.policy: All
